/**
 * FACHARZTPRÜFUNG ANÄSTHESIOLOGIE & INTENSIVMEDIZIN
 * Offizielles Facharzt-Abkürzungsverzeichnis / Kısaltmalar Kılavuzu (DE/TR)
 * Enthält 73 authentische, klinisch hochrelevante Abkürzungen mit Normalwerten & Prüfungsperlen
 */

(function (global) {
  'use strict';

  const ANESTHESIA_ABBREVIATIONS = [
  {
    "abbr": "DLT",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Doppellumentubus (Double-Lumen Tube)",
    "tr_full": "Çift Lümenli Endotrakeal Tüp",
    "de_desc": "Spezialtubus mit zwei getrennten Lumina und Cuffs (tracheal und bronchial) zur seitengetrennten Einlungenventilation (OLV) in der Thoraxchirurgie.",
    "tr_desc": "Toraks cerrahisinde tek akciğer ventilasyonu (OLV) sağlamak için kullanılan çift lümenli ve çift kaf'lı özel tüp. Sol DLT anatomik olarak ilk tercihtir.",
    "exam_pearl": "⚠️ K.O.-Kriterium: Lagekontrolle zwingend fiberoptisch! Trachealer Blick: Carina frei, blauer Bronchuscuff knapp unterhalb im linken Hauptbronchus.",
    "exam_pearl_tr": "⚠️ Sınav K.O. Kriteri: DLT yerleşimi mutlaka fiberoptik bronkoskopiyle doğrulanmalıdır! Karina serbest görülmeli, mavi kaf sol ana bronşta olmalıdır."
  },
  {
    "abbr": "OLV",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Einlungenventilation (One-Lung Ventilation)",
    "tr_full": "Tek Akciğer Ventilasyonu",
    "de_desc": "Gezielte Belüftung nur eines Lungenflügels zur Ruhigstellung des Operationsgebiets bei thorakalen Eingriffen. Erzeugt physiologisch einen Rechts-Links-Shunt.",
    "tr_desc": "Toraks ameliyatlarında cerrahi görüş sağlamak için opere edilen akciğerin söndürülüp sadece diğer akciğerin havalandırılması. Şant fraksiyonunu artırır.",
    "exam_pearl": "⚠️ Akute Hypoxämie unter OLV: 5-Stufen-Plan (1. FiO₂ 1.0 → 2. Bronchoskopie → 3. CPAP 2–5 cmH₂O an kollabierte Lunge → 4. PEEP 5–8 an ventiliertes Organ → 5. Pulmonalarterie klemmen).",
    "exam_pearl_tr": "⚠️ OLV Hipoksemisi Kurtarma Planı: 1. FiO2 1.0 -> 2. Bronkoskopi -> 3. Kollabe akciğere 2-5 cmH2O CPAP -> 4. Bağımlı akciğere PEEP -> 5. Cerrah pulmoner arteri klempler."
  },
  {
    "abbr": "CICO",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Cannot Intubate, Cannot Oxygenate",
    "tr_full": "Entübe Edilemez, Oksijenlenemez Acili",
    "de_desc": "Ultimativer Notfall des schwierigen Atemwegs: Weder Intubation noch Maskenbeatmung oder Supraglottischer Atemweg (LMA) gelingen; akute Asphyxiegefahr.",
    "tr_desc": "Zor havayolunda en ölümcül kriz tablosu: Ne entübasyon, ne yüz maskesi ne de laringeal maske ile oksijenasyon sağlanamaz. Asfiksi kapıdadır.",
    "exam_pearl": "⚠️ Absolutes K.O.-Kriterium: Bei CICO KEINE weiteren frustranen Intubationsversuche! Sofortige chirurgische Koniotomie (Skalpell – Bougie – Tubus ID 6.0 mm)!",
    "exam_pearl_tr": "⚠️ Mutlak K.O. Kriteri: CICO durumunda laringoskopla zaman kaybedilmez! Derhal cerrahi koniotomi (Skalpel - Buji - 6.0 mm Tüp) uygulanır!"
  },
  {
    "abbr": "VL",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Videolaryngoskopie",
    "tr_full": "Videolarengoskopi",
    "de_desc": "Optische Laryngoskopie mit digitaler Kamera an der Spatelspitze (z. B. McGrath, C-MAC, GlideScope). Standardverfahren bei erwartet oder unerwartet schwierigem Atemweg.",
    "tr_desc": "Blade ucundaki kamera ile glottisi ekrana yansıtan cihaz (McGrath, C-MAC vb.). Beklenen veya beklenmeyen zor havayolunda 1. basamak altın standarttır.",
    "exam_pearl": "Hyperangulierte Spatel (D-Blade) erfordern immer einen vorgebogenen Führungsstab / Bougie, da die Blickachse die Instrumentierachse kreuzt.",
    "exam_pearl_tr": "Aşırı açılı blade'lerde (D-Blade) görüş ekseni ile tüp ekseni farklı olduğu için mutlaka önceden bükülmüş stile veya buji kullanılmalıdır."
  },
  {
    "abbr": "SGA",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Supraglottischer Atemweg (Supraglottic Airway)",
    "tr_full": "Supraglottik Havayolu Aracı",
    "de_desc": "Über der Stimmlippenebene platzierte Atemwegshilfen (Larynxmaske, Larynxtubus). 2. Generation mit gastralem Drainagekanal ist Standard.",
    "tr_desc": "Vokal kordların üzerinde yerleşen havayolu araçları (LMA, Laringeal Tüp vb.). Mide drenaj kanallı 2. jenerasyon araçlar altın standarttır.",
    "exam_pearl": "Bei fehlgeschlagener Intubation ist die 2. Generation Larynxmaske das primäre Rettungsinstrument (Plan B im DGAI-Atemwegsalgorithmus).",
    "exam_pearl_tr": "Entübasyon başarısız olduğunda 2. jenerasyon LMA kurtarıcı araçtır (DGAI Plan B)."
  },
  {
    "abbr": "LMA",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Larynxmaske (Laryngeal Mask Airway)",
    "tr_full": "Laringeal Maske",
    "de_desc": "Supraglottische Atemwegshilfe zur Narkosebeatmung bei nüchternen elektiven Patienten oder als Rettungsmittel bei 'Cannot Intubate'.",
    "tr_desc": "Elektif tok olmayan hastalarda anestezi idamesi veya zor havayolunda kurtarıcı ventilasyon için hipofarenkse oturan maske.",
    "exam_pearl": "Maximaler Cuffdruck 60 cmH₂O, um Druckschäden des N. lingualis und N. hypoglossus zu vermeiden.",
    "exam_pearl_tr": "Dil ve hipoglossus sinir felcini önlemek için kaf basıncı en fazla 60 cmH2O olmalıdır."
  },
  {
    "abbr": "FOB",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Fiberoptische Bronchoskopie",
    "tr_full": "Fiberoptik Bronkoskopi",
    "de_desc": "Endoskopische Atemwegssicherung am wachen oder narkotisierten Patienten; Goldstandard bei erwartet schwierigem Atemweg (Wachintubation).",
    "tr_desc": "Uyanık veya anestezili hastada esnek bronkoskopla görüş altında entübasyon. Beklenen zor havayolunda (tümör, ankiloz vb.) altın standarttır.",
    "exam_pearl": "Wachintubation erfordert perfekte topische Schleimhautanästhesie (Lidokain 2–4%) und vorsichtige Sedierung (z. B. Dexmedetomidin oder Remifentanil).",
    "exam_pearl_tr": "Uyanık fiberoptik entübasyonda kusursuz lokal anestezi (Lidokain %2-4) ve solunumu baskılamayan sedasyon (Deksmedetomidin) şarttır."
  },
  {
    "abbr": "FRC",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Funktionelle Residualkapazität",
    "tr_full": "Fonksiyonel Rezidüel Kapasite",
    "de_desc": "Lungenvolumen am Ende einer normalen passiven Exspiration (ERV + RV, ca. 2,5–3,0 l). Dient als physiologischer Sauerstoffspeicher bei Apnoe.",
    "tr_desc": "Normal sakin bir ekspiryum sonunda akciğerde kalan gaz hacmi (yaklaşık 30 ml/kg). Apne sırasında vücudun oksijen deposudur.",
    "exam_pearl": "Drastisch erniedrigt bei Schwangeren, Adipösen (BMI > 35) und in Rückenlage → Apnoetoleranz sinkt von 6–8 Min auf < 1–2 Min!",
    "exam_pearl_tr": "Gebelerde, obezlerde ve yatar pozisyonda FRC belirgin azalır; apneye dayanma süresi 8 dakikadan 1-2 dakikaya düşer!"
  },
  {
    "abbr": "PEEP",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Positiver endexspiratorischer Druck (Positive End-Expiratory Pressure)",
    "tr_full": "Pozitif Ekspiryum Sonu Basınç",
    "de_desc": "Hält die Alveolen am Ende der Ausatmung offen, verhindert Atelektasenbildung, erhöht die FRC und verbessert die Oxygenierung.",
    "tr_desc": "Ekspiryum sonunda havayolunda pozitif basınç tutarak alveollerin sönmesini (kollapsını) önleyen, oksijenasyonu artıran ventilatör parametresi.",
    "exam_pearl": "Standard: 5–8 cmH₂O. Bei ARDS titriert nach ARDSNet (10–18 cmH₂O). Vorsicht: Hoher PEEP senkt den venösen Rückstrom und das HZV!",
    "exam_pearl_tr": "Rutin: 5-8 cmH2O. ARDS'de 10-18 cmH2O. Dikkat: Aşırı PEEP sağ kalbe venöz dönüşü azaltarak tansiyonu düşürür!"
  },
  {
    "abbr": "ΔP (Driving Pressure)",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Treibender Beatmungsdruck (Plateaudruck minus PEEP)",
    "tr_full": "Sürüş Basıncı (Plato Basıncı eksi PEEP)",
    "de_desc": "Differenz aus Plateaudruck und PEEP: ΔP = Pplat - PEEP. Spiegelt die zyklische Alveolarbelastung wider und korreliert direkt mit der Mortalität.",
    "tr_desc": "Plato basıncı ile PEEP arasındaki fark. Akciğerin gerilme stresini yansıtır; ARDS'de sağkalımla en güçlü korelasyon gösteren parametredir.",
    "exam_pearl": "Zielwert strikt: ΔP ≤ 14 cmH₂O! Höhere Werte erzeugen Baro-/Volutrauma und schädigen die Alveolen.",
    "exam_pearl_tr": "Kesin hedef: ΔP <= 14 cmH2O! 14'ün üzerindeki değerler mortaliteyi belirgin artırır."
  },
  {
    "abbr": "Pplat",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Plateau-Beatmungsdruck (Endinspiratorischer Haltedruck)",
    "tr_full": "Plato Basıncı",
    "de_desc": "Gemessener Druck in den Alveolen während eines endinspiratorischen Atemstopps ohne Gasfluss. Maß für die statische Lungencompliance.",
    "tr_desc": "İnspiryum sonunda akım durduğunda ölçülen alveoler basınç. Statik akciğer kompliyansını gösterir.",
    "exam_pearl": "Ziel bei lungenprotektiver Beatmung: Pplat < 30 cmH₂O (besser < 27–28 cmH₂O).",
    "exam_pearl_tr": "Akciğer koruyucu ventilasyonda hedef: Pplat < 30 cmH2O."
  },
  {
    "abbr": "etCO2",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Endtidales Kohlendioxid (End-Tidal CO₂)",
    "tr_full": "Ekspiryum Sonu Karbondioksit Basıncı",
    "de_desc": "Am Ende der Ausatmung gemessene CO₂-Konzentration. Goldstandard zur Tubuslageverifikation und kardialen Auswurfbeurteilung.",
    "tr_desc": "Ekspiryum sonunda ölçülen CO2 parsiyel basıncı (Normal: 35-40 mmHg). Entübasyonun doğrulanmasında ve kalp masajının kalitesinde 1 numaradır.",
    "exam_pearl": "Plötzlicher Absturz (< 15 mmHg): Tubusdislokation, fulminante Lungenembolie oder Herzstillstand! Plötzlicher Anstieg (> 60 mmHg): Maligne Hyperthermie, Hypoventilation oder Bikarbonatgabe!",
    "exam_pearl_tr": "Ani düşüş (< 15 mmHg): Tüp çıkması, masif pulmoner emboli veya kardiyak arrest! Ani yükseliş (> 60 mmHg): Malign hipertermi veya hipoventilasyon!"
  },
  {
    "abbr": "PBW / IBW",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Predicted / Ideal Body Weight (Ideales Körpergewicht)",
    "tr_full": "İdeal / Tahmini Vücut Ağırlığı",
    "de_desc": "Anhand der Körpergröße berechnetes Referenzgewicht zur lungenprotektiven Einstellung des Tidalvolumens (Vt = 6 ml/kg PBW).",
    "tr_desc": "Boy uzunluğuna göre hesaplanan ideal kilo. Lunge-protective mekanik ventilasyonda tidal hacim (6 ml/kg) ASLA gerçek kiloya göre değil, PBW'ye göre ayarlanır.",
    "exam_pearl": "Klassische Falle: Bei 140 kg adipösem Patienten mit 170 cm Größe beträgt das PBW nur ca. 65 kg! Tidalvolumen = 65 x 6 = ca. 390–400 ml!",
    "exam_pearl_tr": "Klasik tuzak: 140 kg obez hastada PBW sadece 65 kg'dır! Tidal volüm 140x6=840 ml değil, 65x6=390 ml ayarlanır!"
  },
  {
    "abbr": "RSI",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Rapid Sequence Induction (Blitzintubation)",
    "tr_full": "Hızlı Seri İndüksiyon",
    "de_desc": "Narkoseeinleitungstechnik bei aspiratorisch gefährdeten Patienten (nicht-nüchtern, Ileus, Schwangerschaft ab 16. SSW, Polytrauma).",
    "tr_desc": "Aspirasyon riski yüksek tok hastalarda aralıksız preoksijenasyon, hızlı etkili hipnotik ve kas gevşetici ile ara solutma yapmadan yapılan entübasyon.",
    "exam_pearl": "Prinzipien: Perfekte Präoxygenierung (3 Min 100%), absaugbereit, Propofol/Thiopental + Rocuronium (1,0–1,2 mg/kg) oder Succinylcholin, KEINE Zwischenbeatmung!",
    "exam_pearl_tr": "%100 O2 preoksijenasyon, aspiratör hazır, yüksek doz Roküronyum (1.0-1.2 mg/kg) veya Süksinilkolin, kaf şişene kadar ARA SOLUTMA YAPILMAZ!"
  },
  {
    "abbr": "NPPE",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Negative Pressure Pulmonary Edema (Unterdrucklungenödem)",
    "tr_full": "Negatif Basınçlı Akciğer Ödemi",
    "de_desc": "Nicht-kardiogenes Lungenödem infolge forcierten Einatmens gegen geschlossene Stimmbänder (z. B. nach Laryngospasmus). Extrem negativer intrathorakaler Druck zieht Flüssigkeit in Alveolen.",
    "tr_desc": "Laringospazmda kapalı glottise karşı güçlü nefes alma çabasıyla (Müller manevrası) intratorasik negatif basıncın fırlaması ve alveollerin plazmayla dolması tablosu.",
    "exam_pearl": "Klinik: Rosafarbener Schaum im Mund nach Laryngospasmus! Therapie: Spasmus lösen (Propofol/Suxamethonium), Re-Intubation, invasive Beatmung mit hohem PEEP (8–12 cmH₂O)!",
    "exam_pearl_tr": "Klinik: Laringospazm sonrası pembe köpüklü balgam! Tedavi: Spazmı çöz, gerekirse re-entübe et, YÜKSEK PEEP (8-12 cmH2O) ile havalandır!"
  },
  {
    "abbr": "SVR",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Systemic Vascular Resistance (Systemvaskulärer Widerstand)",
    "tr_full": "Sistemik Vasküler Direnç (SVR)",
    "de_desc": "Gesamtwiderstand der systemischen Strombahn gegen den linksventrikulären Auswurf. Formel: SVR = (MAP - ZVD) / HZV x 80. Normal: 800–1200 dyn·s·cm⁻⁵.",
    "tr_desc": "Sol ventrikülün kanı periferik damarlara pompalarken karşılaştığı toplam damar direnci. Normal: 800-1200 dyn·s/cm⁵.",
    "exam_pearl": "Bei Aortenklappenstenose und Fallot-Tetralogie muss der SVR zwingend hoch-normal gehalten werden (Noradrenalin/Phenylephrin)! Vasodilatation ist tödlich!",
    "exam_pearl_tr": "Aort darlığında ve Fallot tetralojisinde SVR mutlaka yüksek tutulmalıdır (Noradrenalin/Fenilefrin)! Damar gevşemesi arrest yaptırır!"
  },
  {
    "abbr": "PVR",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Pulmonary Vascular Resistance (Pulmonalvaskulärer Widerstand)",
    "tr_full": "Pulmoner Vasküler Direnç (PVR)",
    "de_desc": "Gefäßwiderstand im Lungenkreislauf. Formel: PVR = (mPAP - PCWP) / HZV x 80. Normal: 100–250 dyn·s·cm⁻⁵.",
    "tr_desc": "Küçük dolaşımdaki (akciğer damar yatağındaki) direnç. Normal: 100-250 dyn·s/cm⁵.",
    "exam_pearl": "PVR steigt massiv bei Hypoxie (Euler-Liljestrand), Hyperkapnie und Azidose! Bei pulmonaler Hypertonie strikt Normoventilation und Azidoseausgleich!",
    "exam_pearl_tr": "PVR; hipoksi, hiperkapni ve asidozda fırlar! Pulmoner hipertansiyonda asidoz ve hipoksiden kesinlikle kaçınılmalıdır."
  },
  {
    "abbr": "MAP / MAD",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Mittlerer arterieller Druck (Mean Arterial Pressure)",
    "tr_full": "Ortalama Arter Basıncı (OAB / MAP)",
    "de_desc": "Perfusionsdruck der Organe im Kapillarbett. Näherungsformel: MAP = Diastole + 1/3 (Systole - Diastole). Normal: 65–90 mmHg.",
    "tr_desc": "Organların kılcal damar düzeyindeki perfüzyonunu belirleyen ortalama basınç. MAP = Diyastol + 1/3 (Sistol - Diyastol).",
    "exam_pearl": "Ziel-MAP: Sepsis ≥ 65 mmHg; Schädel-Hirn-Trauma ≥ 80–90 mmHg; Permissive Hypotonie bei Trauma ohne SHT: 50–60 mmHg.",
    "exam_pearl_tr": "Hedef MAP: Sepsiste >= 65 mmHg; Kafa travmasında >= 80-90 mmHg; Kafa travması olmayan kanamalarda 50-60 mmHg (permissif hipotansiyon)."
  },
  {
    "abbr": "HZV / CO",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Herzzeitvolumen (Cardiac Output)",
    "tr_full": "Kardiyak Debi / Kalp Debisi",
    "de_desc": "Vom Herzen pro Minute gepumptes Blutvolumen. HZV = Schlagvolumen (SV) x Herzfrequenz (HF). Normalwert beim Erwachsenen in Ruhe: 4,5–6,5 l/min.",
    "tr_desc": "Kalbin bir dakikada pompaladığı toplam kan hacmi (Atım Hacmi x Kalp Hızı). Normal: 4.5-6.5 L/dk.",
    "exam_pearl": "Der Cardiac Index (CI = HZV / KOF) normiert das HZV auf die Körperoberfläche. Normaler CI: 2,5–4,0 l/min/m².",
    "exam_pearl_tr": "Vücut yüzeyine oranlanmış debi Kardiyak İndekstir (CI = CO / BSA). Normal: 2.5-4.0 L/dk/m2."
  },
  {
    "abbr": "SVV / PPV",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Schlagvolumenvariation / Pulsdruckvariation",
    "tr_full": "Atım Hacmi Varyasyonu / Nabız Basıncı Varyasyonu",
    "de_desc": "Dynamische Vorlastparameter unter kontrollierter mechanischer Beatmung. Zeigen die Herz-Lungen-Interaktion und die Flüssigkeitsreagibilität.",
    "tr_desc": "Mekanik ventilasyon sırasında intratorasik basınç değişikliklerinin arter dalga formunda oluşturduğu dalgalanma. Sıvı yanıtını gösterir.",
    "exam_pearl": "Gültig NUR bei: Kontrollierter Beatmung (kein Spontanatemzug), Vt ≥ 8 ml/kg, Sinusrhythmus (keine Arrhythmien!). SVV/PPV > 12–13% zeigt Flüssigkeitsbedarf an.",
    "exam_pearl_tr": "SADECE tam kontrollü solunumda (Vt >= 8 ml/kg) ve sinüs ritminde geçerlidir! Değer > %12-13 ise hasta sıvıya yanıt verir."
  },
  {
    "abbr": "ZVD / CVP",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Zentraler Venendruck (Central Venous Pressure)",
    "tr_full": "Santral Venöz Basınç (SVP / CVP)",
    "de_desc": "Im rechten Vorhof bzw. der Vena cava superior gemessener Druck. Normal: 2–8 mmHg (3–10 cmH₂O).",
    "tr_desc": "Vena cava superior veya sağ atriyum girişindeki basınç. Normal: 2-8 mmHg.",
    "exam_pearl": "Statischer Parameter: Taugt NICHT zur Vorhersage von Volumenreagibilität! Wichtig aber zur Berechnung von SVR und Organperfusionsdrücken.",
    "exam_pearl_tr": "Statik bir değerdir; tek başına sıvı ihtiyacını güvenilir GÖSTERMEZ! Ancak SVR ve organ perfüzyon hesabında gereklidir."
  },
  {
    "abbr": "ScvO2",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Zentralvenöse Sauerstoffsättigung",
    "tr_full": "Santral Venöz Oksijen Saturasyonu",
    "de_desc": "Im ZVK (V. cava superior) gemessene Sauerstoffsättigung. Spiegelt das globale Gleichgewicht aus Sauerstoffangebot (DO₂) und Sauerstoffverbrauch (VO₂) wider. Normal: ≥ 70%.",
    "tr_desc": "Santral venöz kateterden alınan kandaki O2 doygunluğu. Oksijen sunumu ile tüketimi arasındaki dengeyi yansıtır. Normal: >= %70.",
    "exam_pearl": "ScvO₂ < 65%: Kardiogener/hypovolämischer Schock oder schwere Anämie. ScvO₂ > 85%: Schwere Sepsis (zytotoxische Hypoxie / Mikrozirkulationsstörung) oder Shunt!",
    "exam_pearl_tr": "ScvO2 < %65: Düşük debi, anemi veya hipovolemi. ScvO2 > %85: Ağır sepsis (dokuların oksijeni kullanamaması / mikrovasküler şant)!"
  },
  {
    "abbr": "TEE / TTE",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Transösophageale / Transthorakale Echokardiographie",
    "tr_full": "Transözofageal / Transtorasik Ekokardiyografi",
    "de_desc": "Ultraschalluntersuchung des Herzens über die Speiseröhre (TEE) oder den Brustkorb (TTE). Goldstandard bei intraoperativer hämodynamischer Instabilität.",
    "tr_desc": "Kalbin yemek borusu içinden (TEE) veya göğüs duvarından (TTE) ultrasonografik incelemesi. İntraoperatif hemodinamik krizlerde en hızlı tanı aracıdır.",
    "exam_pearl": "Fokus im Schock: Füllung LV (Hypovolämie?), Pumpfunktion (Ischämie?), Rechtsherzbelastung (LAE / McConnell-Zeichen?), Perikarderguss (Tamponade?).",
    "exam_pearl_tr": "Şok anında odaklanılacak 4 soru: 1. Sol ventrikül boş mu (hipovolemi)? 2. Pompalıyor mu? 3. Sağ kalp genişlemiş mi (PTE)? 4. Tamponad var mı?"
  },
  {
    "abbr": "PiCCO",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Pulse Contour Cardiac Output",
    "tr_full": "Nabız Kontur Kardiyak Debi Monitörizasyonu",
    "de_desc": "Transpulmonale Thermodislution kombiniert mit kontinuierlicher arterieller Pulskonturanalyse zur erweiterten Schockdifferenzierung.",
    "tr_desc": "Santral venöz soğuk sıvı enjeksiyonu ve femoral arter kateteriyle termodilüsyon ve nabız kontur analizi yapan gelişmiş hemodinami monitörü.",
    "exam_pearl": "Liefert: HZV, GEDV (Vorlast), EVLW (Lungenwasser), SVV/PPV (Volumenreagibilität) und dPmax (Myokardkontraktilität).",
    "exam_pearl_tr": "Sağladığı kritik veriler: CO, GEDV (gerçek ön yük), EVLW (akciğer ödemi derecesi), SVV (sıvı yanıtı), dPmax (kasılma gücü)."
  },
  {
    "abbr": "NIRS",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Nahinfrarotspektroskopie (Near-Infrared Spectroscopy)",
    "tr_full": "Yakın Kızılötesi Spektroskopi (Serebral Oksimetri)",
    "de_desc": "Nicht-invasives optisches Neuromonitoring zur kontinuierlichen Messung der regionalen zerebralen Sauerstoffsättigung (rSO₂). Normalwert: 60–80%.",
    "tr_desc": "Alına yapıştırılan optik sensörlerle beyin korteksindeki mikrovasküler hemoglobin satürasyonunu (rSO2) ölçen non-invaziv cihaz.",
    "exam_pearl": "Kardinaler Prüfungsfall (Karotischirurgie): Fällt der NIRS-Wert um > 20% gegenüber dem Ausgangswert, besteht zwingende Indikation zur Shunt-Einlage!",
    "exam_pearl_tr": "Kritik sınav kuralı (Karotis ameliyatı): Klempleme sonrası NIRS bazale göre > %20 düşerse MUTLAKA geçici intraarteriyel şant konulur!"
  },
  {
    "abbr": "AKS",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Aortenklappenstenose",
    "tr_full": "Aort Kapak Darlığı",
    "de_desc": "Verengung der Aortenklappe mit Druckbelastung und konzentrischer Hypertrophie des linken Ventrikels. Schwere AKS: Klappenöffnungsfläche < 1,0 cm², mittlerer Gradient > 40 mmHg.",
    "tr_desc": "Aort kapağının daralması; sol ventrikülde aşırı basınç yükü ve konsantrik hipertrofiye yol açar. Ağır AKS: Kapak alanı < 1.0 cm2, ortalama gradyan > 40 mmHg.",
    "exam_pearl": "⚠️ ÄKNO K.O.-Kriterium: SPINALANÄSTHESIE IST ABSOLUT KONTRAINDIZIERT! Hämodynamik: SVR hoch halten (Noradrenalin), Vorlast sichern, Sinusrhythmus 60–80/min!",
    "exam_pearl_tr": "⚠️ ÄKNO K.O. Kriteri: SPİNAL ANESTEZİ KESİNLİKLE YASAKTIR! SVR yüksek tutulmalı (Noradrenalin), ön yük korunmalı, 60-80/dk sinüs ritmi sağlanmalıdır!"
  },
  {
    "abbr": "HOCM",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Hypertrophische obstruktive Kardiomyopathie",
    "tr_full": "Hipertrofik Obstrüktif Kardiyomiyopati",
    "de_desc": "Genetische asymmetrische Septumhypertrophie mit dynamischer linksventrikulärer Ausflusstraktobstruktion (LVOTO) und 'Systolic Anterior Motion' (SAM) des vorderen Mitralsegels.",
    "tr_desc": "İnterventriküler septumun genetik kalınlaşması; sistolde aort çıkım yolunu daraltır (SAM fenomeni).",
    "exam_pearl": "K.O.-Falle: INOTROPIKA (Dobutamin/Adrenalin) SIND KONTRAINDIZIERT! Sie verstärken den SAM-Effekt drastisch. Therapie: Betablocker, Vorlast ↑, SVR ↑ (Phenylephrin/Noradrenalin).",
    "exam_pearl_tr": "K.O. Tuzağı: İNOTROP İLAÇLAR (Dobutamin/Adrenalin) KONTRENDİKEDİR! Tıkanmayı artırır. Tedavi: Beta bloker, volüm yükleme, SVR'yi artırma!"
  },
  {
    "abbr": "LAE / PTE",
    "category": "hemodynamics",
    "category_de": "Hämodynamik, Kardiologie & Monitoring",
    "category_tr": "Hemodinami, Kardiyoloji & Monitörizasyon",
    "de_full": "Lungenarterienembolie (Pulmonary Embolism)",
    "tr_full": "Pulmoner Tromboemboli (PTE)",
    "de_desc": "Akute Verlegung der Pulmonalarterienäste durch Thromben; führt zu partiellem Totraum, akutem Rechtsherzversagen und Kreislaufkollaps.",
    "tr_desc": "Pulmoner damar yatağının ani pıhtıyla tıkanması; akut sağ kalp yetmezliği ve obstrüktif şok tablosu oluşturur.",
    "exam_pearl": "Klassische Trias im OP: etCO₂ stürzt akut ab (< 15 mmHg), arterieller Druck fällt, Beatmungsdruck steigt! Therapie bei Schock: Sofortige Lyse (Alteplase 50–100 mg i.v.)!",
    "exam_pearl_tr": "Ameliyathanede klasik belirti: etCO2 aniden çakılır (< 15 mmHg), tansiyon çöker, sağ kalp yetmezliği gelişir! Şokta tedavi: Acil tromboliz (Alteplaz 50-100 mg i.v.)!"
  },
  {
    "abbr": "TIVA",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Total Intravenöse Anästhesie",
    "tr_full": "Total İntravenöz Anestezi",
    "de_desc": "Ausschließliche Gabe von intravenösen Anästhetika (typisch Propofol + Remifentanil) ohne volatile Inhalationsanästhetika.",
    "tr_desc": "İnhalasyon gazları kullanılmadan, sadece damar içi ajanlarla (tipik olarak Propofol + Remifentanil) yürütülen genel anestezi.",
    "exam_pearl": "Vorteile: Kaum PONV, keine Triggerung von Maligner Hyperthermie (MH), keine ICP-Steigerung (ideal für Neuroanästhesie). Cave: Awareness-Gefahr bei Perfusorstopp!",
    "exam_pearl_tr": "Üstünlükleri: Sıfır MH riski, minimal PONV, kafa içi basıncını düşürür. Dikkat: Damar yolu tıkanırsa hasta uyanabilir (awareness)!"
  },
  {
    "abbr": "MAC",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Minimale Alveoläre Konzentration",
    "tr_full": "Minimal Alveoler Konsantrasyon (MAK)",
    "de_desc": "Alveoläre Konzentration eines Inhalationsanästhetikums bei 1 atm, bei der 50% der Patienten auf einen standardisierten Hautschnitt nicht mehr mit Abwehrbewegungen reagieren.",
    "tr_desc": "1 atmosfer basınçta, hastaların %50'sinde cerrahi cilt kesisine karşı motor cevabı engelleyen alveoler anestezik gaz konsantrasyonu.",
    "exam_pearl": "Referenzwerte beim 40-Jährigen: Sevofluran ca. 2,0 Vol-%; Desfluran ca. 6,0 Vol-%; Isofluran ca. 1,15 Vol-%. MAC sinkt im Alter um ca. 6% pro Dekade!",
    "exam_pearl_tr": "40 yaş referans değerleri: Sevofluran %2.0; Desfluran %6.0; İzofluran %1.15. Yaşlandıkça her 10 yılda MAC yaklaşık %6 azalır!"
  },
  {
    "abbr": "TOF",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Train-of-Four (Vierfachstimulation)",
    "tr_full": "Train-of-Four (Dörtlü Uyarı Pulu)",
    "de_desc": "Vier supramaximale elektrische Reize im Abstand von 0,5 s (2 Hz). TOF-Ratio = Amplitude 4. Zuckung / Amplitude 1. Zuckung (T4/T1).",
    "tr_desc": "Nöromüsküler iletimi ölçmek için periferik sinire 2 Hz frekansta uygulanan 4 elektrik uyarısı. TOF oranı = 4. yanıt / 1. yanıt genliği.",
    "exam_pearl": "⚠️ ÄKNO Kardinalkriterium: Sichere Extubation erfordert quantitativ verifizierte TOF-Ratio ≥ 0,90 (90%)! Klinische Tests (z. B. Kopfheben 5s) reichen keinesfalls aus.",
    "exam_pearl_tr": "⚠️ ÄKNO Temel Kuralı: Güvenli ekstübasyon için kantitatif ölçümde TOF oranı MUTLAKA >= 0.90 (%90) olmalıdır! Baş kaldırma gibi testler yetersizdir."
  },
  {
    "abbr": "PTC",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Post-Tetanic Count (Posttetanische Zählung)",
    "tr_full": "Post-Tetanik Sayım (PTC)",
    "de_desc": "Messmethode für sehr tiefen neuromuskulären Block (wenn TOF = 0). 50 Hz Tetanus für 5 s, gefolgt von Einzelzuckungen nach 3 s Pause.",
    "tr_desc": "TOF yanıtı sıfır olduğunda (derin blok) uygulanan özel tetanik uyarı testi. Tetanustan sonra beliren tekil kas seğirmeleri sayılır.",
    "exam_pearl": "PTC 1–2: Tiefer Block → Sugammadex 4 mg/kg i.v. erforderlich. TOF 1–2: Moderater Block → Sugammadex 2 mg/kg i.v. Notfall-Rescue: 16 mg/kg!",
    "exam_pearl_tr": "PTC 1-2: Derin blok -> Sugammadeks 4 mg/kg. TOF 1-2: Orta blok -> Sugammadeks 2 mg/kg. Acil kurtarma (Rocuronium sonrası CICO): 16 mg/kg!"
  },
  {
    "abbr": "LAST",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Local Anesthetic Systemic Toxicity (Lokalanästhetika-Intoxikation)",
    "tr_full": "Lokal Anestezik Sistemik Toksisitesi (LAST)",
    "de_desc": "Lebensbedrohliche Intoxikation des ZNS und Herzens durch versehentliche intravasale Injektion oder massive Resorption von Lokalanästhetika (z. B. Bupivacain).",
    "tr_desc": "Lokal anesteziklerin damar içine kazara verilmesi veya aşırı emilmesi sonucu santral sinir sistemi ve kalpte gelişen ölümcül toksisite tablosu.",
    "exam_pearl": "⚠️ K.O.-Kriterium: Antidot ist LIPID 20% (Intralipid): Sofort 1,5 ml/kg Bolus i.v. über 1 Min, dann 0,25 ml/kg/min! Vasopressin und Lidocain sind STRENG KONTRAINDIZIERT!",
    "exam_pearl_tr": "⚠️ K.O. Kriteri: Spesifik antidot LİPİD EMÜLSİYONU %20'dir: Hemen 1.5 ml/kg bolus, ardından 0.25 ml/kg/dk infüzyon! Vazopressin ve Lidokain KESİNLİKLE YASAKTIR!"
  },
  {
    "abbr": "MH",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Maligne Hyperthermie",
    "tr_full": "Malign Hipertermi",
    "de_desc": "Pharmakogenetische myogene Stoffwechselentgleisung des Ryanodin-Rezeptors (RYR1) getriggert durch volatile Anästhetika oder Succinylcholin.",
    "tr_desc": "Uçucu anestezik gazlar veya Süksinilkolin ile tetiklenen, kontrolsüz kalsiyum salınımıyla giden ölümcül iskelet kası hipermetabolizma krizi.",
    "exam_pearl": "⚠️ K.O.-Kriterium: 1. Trigger STOPPEN, 2. 100% O₂ High Flow, 3. DANTROLEN 2,5 mg/kg i.v. (bis 10 mg/kg)! Kalziumantagonisten (Verapamil) sind TÖDLICH KONTRAINDIZIERT!",
    "exam_pearl_tr": "⚠️ K.O. Kriteri: 1. Tetikleyiciyi KES, 2. %100 O2 High Flow, 3. DANTROLEN 2.5 mg/kg i.v.! Kalsiyum kanal blokerleri (Verapamil) ÖLÜMCÜL KONTRENDİKEDİR!"
  },
  {
    "abbr": "ZAS",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Zentrales Anticholinerges Syndrom",
    "tr_full": "Santral Antikolinerjik Sendrom",
    "de_desc": "Zerebrale Blockade muskarinischer Rezeptoren durch Anästhetika, Opioide oder Atropin. Symptome: Postoperative Verwirrtheit, Delir, Halluzinationen, Mydriasis, warme trockene Haut.",
    "tr_desc": "Santral kolinerjik iletimin baskılanması sonucu ayılma odasında gelişen ajitasyon, deliryum, midriyazis, taşikardi ve cilt kuruluğu tablosu.",
    "exam_pearl": "Spezifisches Antidot: PHYSOSTIGMIN (Anticholium) 1–2 mg langsam i.v. (überwindet im Gegensatz zu Neostigmin die Blut-Hirn-Schranke!).",
    "exam_pearl_tr": "Spesifik panzehir: FİZOSTİGMİN 1-2 mg yavaş i.v. (Neostigminin aksine kan-beyin bariyerini geçer!)."
  },
  {
    "abbr": "BIS",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Bispektraler Index",
    "tr_full": "Bispektral İndeks (BIS)",
    "de_desc": "Verarbeitetes EEG-Signal zur quantitativen Überwachung der Narkosetiefe auf einer Skala von 0 (Nulllinie) bis 100 (wach).",
    "tr_desc": "Kortikal EEG dalgalarını analiz ederek 0 (izoelektrik hat) ile 100 (uyanık) arasında anestezi derinliği skorlayan non-invaziv monitörizasyon.",
    "exam_pearl": "Zielbereich während Allgemeinanästhesie: 40–60. Werte > 60: Awareness-Gefahr (Narkose vertiefen!). Werte < 40: Zu tief (Burst Suppression, Hypotonie).",
    "exam_pearl_tr": "Genel anestezide hedef: 40-60. > 60: Uyanıklık/farkındalık riski (anesteziyi derinleştir!). < 40: Aşırı derin (burst süpresyonu)."
  },
  {
    "abbr": "PONV",
    "category": "pharma",
    "category_de": "Pharmakologie & Narkosetiefe",
    "category_tr": "Farmakoloji & Anestezi Derinliği",
    "de_full": "Postoperative Nausea and Vomiting (Übelkeit & Erbrechen)",
    "tr_full": "Postoperatif Bulantı ve Kusma",
    "de_desc": "Häufige postoperative Komplikation. Risikoeinschätzung nach dem Apfel-Score (weiblich, Nichtraucher, PONV/Kinetose in Anamnese, postoperative Opioide).",
    "tr_desc": "Ameliyat sonrası bulantı-kusma. Apfel skoruyla (kadın, sigara içmeyen, PONV öyküsü, postoperatif opioid) risk belirlenir.",
    "exam_pearl": "Ab 2 Risikofaktoren: Multimodale Prophylaxe (Dexamethason 4–8 mg bei Einleitung + Ondansetron 4 mg am OP-Ende, TIVA erwägen).",
    "exam_pearl_tr": ">= 2 risk faktöründe multimodal profilaksi: İndüksiyonda Deksametazon 4-8 mg + operasyon sonunda Ondansetron 4 mg + TIVA tercihi."
  },
  {
    "abbr": "ALS",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Advanced Life Support (Erweiterte Reanimation)",
    "tr_full": "İleri Yaşam Desteği",
    "de_desc": "Leitliniengerechte Reanimation nach ERC/AHA mit EKG-Rhythmusdiagnostik, Defibrillation, Atemwegssicherung und Notfallmedikamenten.",
    "tr_desc": "ERC/AHA kılavuzlarına göre ritim analizi, defibrilasyon, ileri havayolu ve ilaç uygulamalarını içeren profesyonel kardiyopulmoner canlandırma.",
    "exam_pearl": "Schockbare Rhythmen (VF/pVT): 1. Schock → 2 Min CPR → 2. Schock → 2 Min CPR → 3. Schock → DANN ERST Adrenalin 1 mg + Amiodaron 300 mg i.v.!",
    "exam_pearl_tr": "Şoklanabilir ritimlerde (VF/pVT): Adrenalin 1 mg ve Amiodaron 300 mg ANCAK 3. ŞOKTAN SONRA verilir! Öncesinde sadece göğüs basısı ve şok!"
  },
  {
    "abbr": "ROSC",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Return of Spontaneous Circulation",
    "tr_full": "Spontan Dolaşımın Geri Dönmesi",
    "de_desc": "Wiederkehr eines tastbaren Spontanpulses nach Herz-Kreislauf-Stillstand. Sofortige Einleitung des Post-Reanimations-Managements.",
    "tr_desc": "Kardiyak arrest sonrasında palpabl nabzın ve organize dolaşımın geri gelmesi.",
    "exam_pearl": "Sicherstes Zeichen unter CPR: Plötzlicher steiler Anstieg des etCO₂ auf > 35–40 mmHg! Danach: TTM (32–36°C), MAP ≥ 65–70, Koronarangiographie.",
    "exam_pearl_tr": "CPR sırasında en güvenilir ROSC belirtisi: etCO2 değerinin aniden > 35-40 mmHg'ye fırlamasıdır! Ardından hedefli sıcaklık yönetimi başlar."
  },
  {
    "abbr": "4H & HITS",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Reversible Ursachen des Herz-Kreislauf-Stillstands",
    "tr_full": "Geri Döndürülebilir Kardiyak Arrest Nedenleri",
    "de_desc": "Strukturierte Checkliste bei pulsloser elektrischer Aktivität (PEA) und Asystolie nach ERC-Leitlinie.",
    "tr_desc": "PEA ve asistolide kardiyak arresti geri çevirmek için derhal taranması gereken 8 temel neden.",
    "exam_pearl": "4H: Hypoxie, Hypovolämie, Hypo-/Hyperkaliämie (u. metabolisch), Hypothermie. HITS: Herzbeuteltamponade, Intoxikation, Thromboembolie (LAE/KHK), Spannungspneumothorax.",
    "exam_pearl_tr": "4H: Hipoksi, Hipovolemi, Hipo/Hiperkalemi (asidoz), Hipotermi. HITS: Kalp tamponadı, İntoksikasyon, Tromboemboli (PTE/MI), Tansiyon pnömotoraks."
  },
  {
    "abbr": "ROTEM",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Rotationsthromboelastometrie",
    "tr_full": "Rotasyonel Tromboelastometri",
    "de_desc": "Viskoelastisches Point-of-Care-Gerinnungsmessverfahren zur schnellen Differenzierung von Gerinnungsstörungen bei massiver Blutung binnen 10–15 Min.",
    "tr_desc": "Masif kanamada pıhtı oluşumu, sertliği ve erimesini 10 dakikada yatak başında analiz eden viskoelastik hemostaz cihazı.",
    "exam_pearl": "Parameter: CT (Clotting Time, Faktorenmangel?) → CFT (Bildungszeit) → MCF (maximale Festigkeit). Differenzierung über EXTEM, INTEM, FIBTEM, APTEM, HEPTEM.",
    "exam_pearl_tr": "Temel parametreler: CT (faktör eksikliği), CFT (oluşum hızı), MCF (pıhtı gücü). EXTEM, INTEM, FIBTEM, APTEM testleriyle spesifik tedavi seçilir."
  },
  {
    "abbr": "FIBTEM",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Fibrinogen-spezifischer ROTEM-Test (Cytochalasin D)",
    "tr_full": "FIBTEM (Trombositsiz Saf Fibrinojen Ölçümü)",
    "de_desc": "Inaktiviert Thrombozyten durch Cytochalasin D vollständig; die gemessene Gerinnselfestigkeit spiegelt rein den Fibrinogenanteil wider.",
    "tr_desc": "Cytochalasin D ile trombositleri felç ederek geriye kalan saf fibrin ağının gücünü ölçen ROTEM testi.",
    "exam_pearl": "⚠️ ÄKNO Prüfungsperle: FIBTEM A10 < 10 mm (bzw. MCF < 12 mm) ist die zwingende Indikation zur FIBRINOGEN-Substitution (2–4 g i.v.)! Ziel: A10 ≥ 10–12 mm.",
    "exam_pearl_tr": "⚠️ Kritik Eşik: FIBTEM A10 < 10 mm ise İLK İŞ 2-4 g FİBRİNOJEN vermektir! FFP beklenmez, hedef A10 >= 10-12 mm'dir."
  },
  {
    "abbr": "TXA",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Tranexamsäure",
    "tr_full": "Traneksamik Asit",
    "de_desc": "Synthetisches Antifibrinolytikum; blockiert die Lysin-Bindungsstellen von Plasminogen und hemmt so den vorzeitigen Fibrinabbau.",
    "tr_desc": "Plazminojeni bloke ederek pıhtının erken erimesini (hiperfibrinolizi) önleyen hayat kurtarıcı antifibrinolitik ilaç.",
    "exam_pearl": "Dosierung beim Schwerverletzten / PPH (CRASH-2): 1 g i.v. als Kurzinfusion über 10 Min, gefolgt von 1 g über 8 Stunden. MUSS BINNEN DER ERSTEN 3 STUNDEN GEGEBEN WERDEN!",
    "exam_pearl_tr": "Travma ve postpartum kanamada doz: 1 g i.v. bolus (10 dk) + 1 g infüzyon (8 saat). KAZADAN SONRAKİ İLK 3 SAAT İÇİNDE VERİLMESİ ŞARTTIR!"
  },
  {
    "abbr": "PCC / PPSB",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Prothrombinkomplex-Konzentrat (Prothrombin, Proconvertin, Stuart-Prower, B-Faktor)",
    "tr_full": "Protrombin Kompleks Konsantresi (Faktör II, VII, IX, X)",
    "de_desc": "4-Faktoren-Konzentrat der Vitamin-K-abhängigen Gerinnungsfaktoren (Faktor II, VII, IX, X sowie Protein C und S) zur raschen Antikoagulationsumkehr.",
    "tr_desc": "K vitaminine bağımlı pıhtılaşma faktörlerini (II, VII, IX, X) içeren konsantre. Kumarin ve DOAK kanamalarını hızla durdurur.",
    "exam_pearl": "Dosierung: 25–50 IE/kg i.v. Indikation: Schnelle Aufhebung von Phenprocoumon (Marcumar), Notfallantagonisierung von Faktor-Xa-Inhibitoren (Rivaroxaban/Apixaban).",
    "exam_pearl_tr": "Doz: 25-50 IU/kg i.v. Endikasyon: Marcumar etkisini sıfırlamak veya DOAK (Rivaroksaban/Apiksaban) masif kanamasında pıhtılaşmayı sağlamak."
  },
  {
    "abbr": "DOAK / NOAK",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Direkte / Neue Orale Antikoagulanzien",
    "tr_full": "Doğrudan Etkili Oral Antikoagülanlar",
    "de_desc": "Direkte Gerinnungsinhibitoren: Direkte Thrombininhibitoren (Dabigatran) und direkte Faktor-Xa-Inhibitoren (Rivaroxaban, Apixaban, Edoxaban).",
    "tr_desc": "Doğrudan trombin (Dabigatran) veya Faktör Xa'yı (Rivaroksaban, Apiksaban, Edoksaban) hedef alan yeni nesil kan sulandırıcılar.",
    "exam_pearl": "DGAI-Pausen vor rückenmarksnaher Regionalanästhesie: Normalbefund mind. 48h! Bei Niereninsuffizienz (GFR < 50 ml/min) mind. 72h Karenz!",
    "exam_pearl_tr": "Spinal/Epidural öncesi bekleme süresi: Normal böbrekte en az 48 saat! Böbrek yetmezliğinde (GFR < 50) EN AZ 72 SAAT beklenmelidir!"
  },
  {
    "abbr": "ACT",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Gerinnung",
    "category_tr": "Acil Tıp, CPR & Hemostaz",
    "de_full": "Activated Clotting Time (Aktivierte Gerinnungszeit)",
    "tr_full": "Aktive Pıhtılaşma Zamanı",
    "de_desc": "Point-of-Care-Test zur Überwachung hoher Heparindosierungen, insbesondere während des kardiopulmonalen Bypasses an der Herz-Lungen-Maschine (HLM).",
    "tr_desc": "Kalp-akciğer makinesinde ve damar cerrahisinde yüksek doz heparinin etkisini yatak başında izleyen test.",
    "exam_pearl": "Basalwert: 100–140 s. Zielwert für den Anschluss der Herz-Lungen-Maschine: ACT > 400–480 Sekunden! Antagonisierung mit Protamin (1 mg pro 100 IE Heparin).",
    "exam_pearl_tr": "Normal: 100-140 sn. Kalp-akciğer makinesine giriş için HEDEF: ACT > 400-480 saniye! Nötralizasyon: Protamin (her 100 IU heparine 1 mg)."
  },
  {
    "abbr": "CPP",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Cerebral Perfusion Pressure (Zerebraler Perfusionsdruck)",
    "tr_full": "Serebral Perfüzyon Basıncı (SPB / CPP)",
    "de_desc": "Effektiver Netto-Blutdruckgradient über dem Gehirnbett. Formel: CPP = MAP - ICP (bzw. ZVD, falls ZVD > ICP). Normal: 60–80 mmHg.",
    "tr_desc": "Beyin dokusunu perfüze eden net basınç farkı. Formül: CPP = MAP - ICP. Normal: 60-80 mmHg.",
    "exam_pearl": "⚠️ ÄKNO K.O.-Kriterium: Bei Schädel-Hirn-Trauma (SHT) muss der CPP strikt ≥ 60–70 mmHg gehalten werden! Permissive Hypotonie ist bei SHT STRENG KONTRAINDIZIERT!",
    "exam_pearl_tr": "⚠️ ÄKNO K.O. Kriteri: Travmatik beyin hasarında hedef CPP >= 60-70 mmHg'dir! Kafa travmasında tansiyonun düşürülmesine KESİNLİKLE İZİN VERİLMEZ!"
  },
  {
    "abbr": "ICP",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Intracranial Pressure (Intrakranieller Druck / Hirndruck)",
    "tr_full": "Kafa İçi Basıncı (KİB / ICP)",
    "de_desc": "Druck im starren Schädel (Monro-Kellie-Doktrin: Gehirn, Blut, Liquor). Normalwert in Ruhe: 5–15 mmHg. Therapiebedürftig ab > 20–22 mmHg.",
    "tr_desc": "Kafatası içindeki basınç (Monro-Kellie doktrini). Normal: 5-15 mmHg. Kritik sınır: > 20-22 mmHg acil tedavi gerektirir.",
    "exam_pearl": "Hirndrucktherapie-Stufen: 1. Oberkörper 30° hoch, 2. Normoventilation (etCO₂ 35), 3. Osmotherapie (Mannitol 20% 0,5–1 g/kg oder NaCl 3%), 4. Vertiefung / Barbiturate, 5. Kraniektomie.",
    "exam_pearl_tr": "KİB düşürme basamakları: 1. Başı 30° kaldır, 2. Normoventilasyon (etCO2 35), 3. Osmoterapi (Mannitol %20 veya NaCl %3), 4. Derinleştirme/Barbitürat, 5. Dekompresif cerrahi."
  },
  {
    "abbr": "CMRO2",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Cerebral Metabolic Rate of Oxygen (Zerebraler Sauerstoffverbrauch)",
    "tr_full": "Beyin Oksijen Tüketim Metabolizması (CMRO2)",
    "de_desc": "Sauerstoffbedarf des Gehirngewebes. Normalwert: ca. 3,0–3,5 ml O₂ / 100 g Hirngewebe / min.",
    "tr_desc": "Beyin dokusunun birim zamandaki oksijen tüketim hızı. Normal: 3.0-3.5 ml O2 / 100g / dk.",
    "exam_pearl": "Propofol und Barbiturate senken CMRO₂ und CBF parallel (ideale Koppelung). Ketamin steigert CMRO₂ und Hirndruck!",
    "exam_pearl_tr": "Propofol ve tiyopental CMRO2 ve beyin kan akımını paralel düşürür (beyni korur). Ketamin ise CMRO2 ve kafa içi basıncını artırır!"
  },
  {
    "abbr": "CBF",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Cerebral Blood Flow (Zerebraler Blutfluss)",
    "tr_full": "Serebral Kan Akımı (CBF)",
    "de_desc": "Durchblutung des Gehirns. Normalwert: ca. 50 ml / 100 g / min. Bleibt über Autoregulation bei MAP 50–150 mmHg konstant.",
    "tr_desc": "Beynin birim dokusundan geçen kan miktarı (Normal: 50 ml/100g/dk). Normalde MAP 50-150 mmHg arasında otoregülasyonla sabit tutulur.",
    "exam_pearl": "Extreme CO₂-Reaktivität: Jedes mmHg PaCO₂-Änderung verändert den CBF um 2–4%! Hyperkapnie erzeugt Hirnödem; forcierte Hyperventilation (PaCO₂ < 30) erzeugt zerebrale Ischämie!",
    "exam_pearl_tr": "PaCO2'deki her 1 mmHg değişim beyin kan akımını %2-4 değiştirir! Hiperkapni beyni şişirir; aşırı hiperventilasyon ise damarları büzüp iskemi yapar!"
  },
  {
    "abbr": "SAB",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Subarachnoidalblutung",
    "tr_full": "Subaraknoid Kanama (SAK)",
    "de_desc": "Blutung in den Liquorraum zwischen Arachnoidea und Pia mater, meist durch Ruptur eines zerebralen Aneurysmas (A. communicans ant., A. basilaris).",
    "tr_desc": "Genellikle anevrizma rüptürüne bağlı subaraknoid mesafeye kanama tablosu ('hayatımın en şiddetli baş ağrısı').",
    "exam_pearl": "Re-Ruptur-Prävention: Transmuralen Aneurysmadruck (MAP - ICP) streng stabil halten! Nimodipin (60 mg alle 4h p.o. / Perfusor) zur Vasospasmusprophylaxe.",
    "exam_pearl_tr": "Tekrar kanamayı önlemek için indüksiyonda tansiyon fırlaması engellenmelidir! Vazospazm profilaksisinde NİMODİPİN başlanır."
  },
  {
    "abbr": "SPA / EDA",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Spinalanästhesie / Epiduralanästhesie (Periduralanästhesie / PDA)",
    "tr_full": "Spinal Anestezi / Epidural Anestezi",
    "de_desc": "Rückenmarksnahe Regionalanästhesieverfahren: SPA injiziert intrathekal in den Liquor (L3/4 oder L4/5); EDA platziert einen Katheter im Periduralraum.",
    "tr_desc": "Santral nöroaksiyel bloklar: Spinal anestezi subaraknoid mesafeye (L3-L4 veya L4-L5); epidural anestezi dura dışındaki peridural alana uygulanır.",
    "exam_pearl": "Kardiale Sympathikolyse (T1–T4 Block): Führt zu schwerer Bradykardie und Hypotonie! Therapie: Atropin 0,5–1 mg + Adrenalin 10–20 µg i.v. Nicht in Kopftieflage bringen!",
    "exam_pearl_tr": "Yüksek blokta (T1-T4 kardiyoakseleratör lifler felç) derin bradikardi ve şok gelişir! Tedavi: Atropin 0.5-1 mg + Adrenalin. Hasta Trendelenburg'a ALINMAZ!"
  },
  {
    "abbr": "ESP / TAP",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Erector Spinae Plane / Transversus Abdominis Plane Block",
    "tr_full": "ESP Bloğu / TAP Bloğu",
    "de_desc": "Ultraschallgestützte Faszienschichtblöcke der Rumpfwand zur postoperativen Schmerztherapie nach Thorax- bzw. Laparotomie-Eingriffen.",
    "tr_desc": "Toraks ve batın cerrahisi sonrası somatik ağrıyı kesmek için ultrason altında fasya planlarına lokal anestezik enjeksiyonu.",
    "exam_pearl": "Hohes Resorptionsgebiet für Lokalanästhetika! Maximaldosen strikt beachten (Ropivacain max. 3 mg/kg), LAST-Gefahr überwachen!",
    "exam_pearl_tr": "Geniş emilim alanıdır! Maksimum lokal anestezik dozuna (Ropivakain maks 3 mg/kg) çok dikkat edilmelidir; LAST riski taşır."
  },
  {
    "abbr": "EEZ",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Entschluss-Entbindungs-Zeit (Decision-to-Delivery Interval)",
    "tr_full": "Karar-Doğum Süresi (E-E-Zeit)",
    "de_desc": "Zeitspanne zwischen der Indikationsstellung zur Notsectio (Kategorie 1) und der tatsächlichen Kindsentwicklung.",
    "tr_desc": "Kategori 1 acil sezaryen (Cito-Sectio) kararının verilmesi ile bebeğin doğumu arasında geçen süre.",
    "exam_pearl": "Leitliniengrenze: Maximal 20 Minuten (klinikintern meist ≤ 15 Min angestrebt), um hypoxische neonatale Enzephalopathien zu verhindern.",
    "exam_pearl_tr": "Kılavuz sınırı: En fazla 20 DAKİKA (birçok klinikte hedef <= 15 dk)! Bebeğin hipoksik beyin hasarını önlemek için şarttır."
  },
  {
    "abbr": "HELLP",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Hemolysis, Elevated Liver enzymes, Low Platelets",
    "tr_full": "HELLP Sendromu",
    "de_desc": "Schwere Verlaufsform der Präeklampsie: Hämolyse (LDH ↑), Transaminasenanstieg (ASAT/ALAT ↑) und Thrombozytopenie (< 100.000/µl).",
    "tr_desc": "Ağır preeklampsi tablosu: Hemoliz (LDH yüksekliği), karaciğer enzim yüksekliği ve trombosit düşüklüğü.",
    "exam_pearl": "Regionalanästhesie-Grenze: Bei Thrombozyten < 70.000–80.000/µl (oder rapide fallend) KEINE Spinal-/Periduralanästhesie (Gefahr des spinalen Epiduralhämatoms)!",
    "exam_pearl_tr": "Trombosit < 70.000-80.000/µL ise veya hızla düşüyorsa SPİNAL/EPİDURAL KONTRENDİKEDİR (spinal hematom felç riski)!"
  },
  {
    "abbr": "VCI",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Vena Cava Inferior (Cava-Kompressionssyndrom)",
    "tr_full": "Vena Kava İnferior Bası Sendromu",
    "de_desc": "Kompression der unteren Hohlvene durch den graviden Uterus in Rückenlage ab der 20. SSW; führt zu drastischem Vorlastabfall, Schock und fetaler Bradykardie.",
    "tr_desc": "Gebenin sırtüstü yatmasıyla büyümüş uterusun alt ana toplardamara bası yapması; venöz dönüş çöker, anne bayılır, bebek bradikardiye girer.",
    "exam_pearl": "⚠️ ÄKNO Prüfungsregel: Schwangere im OP IMMER 15–30° nach LINKS kippen (Keil unter die rechte Hüfte), um die Vena cava zu entlasten!",
    "exam_pearl_tr": "⚠️ Altın Kural: Ameliyathanede gebe kadın MUTLAKA 15-30° SOLA EĞİMLİ yatırılır (sağ kalça altına takoz)!"
  },
  {
    "abbr": "CAM-ICU",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Confusion Assessment Method for the Intensive Care Unit",
    "tr_full": "Yoğun Bakım Deliryum Değerlendirme Yöntemi",
    "de_desc": "Validiertes Screening-Instrument zur raschen Erkennung eines Delirs bei beatmeten und nicht-beatmeten Intensivpatienten.",
    "tr_desc": "Yoğun bakımda entübe ve non-entübe hastalarda deliryumu hızla teşhis etmek için kullanılan standart tarama testi.",
    "exam_pearl": "Kriterien: 1. Akuter Beginn/fluktuierender Verlauf + 2. Inattention (Aufmerksamkeitsstörung) + ENTWEDER 3. Verändertes Bewusstseinsniveau ODER 4. Desorganisiertes Denken.",
    "exam_pearl_tr": "Pozitiflik: 1. Akut başlangıç/dalgalı seyir + 2. Dikkat bozukluğu + (3. Değişmiş bilinç düzeyi VEYA 4. Dezorganize düşünce)."
  },
  {
    "abbr": "SOFA / qSOFA",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Sequential Organ Failure Assessment (Sepsis-3)",
    "tr_full": "Sıralı Organ Yetmezliği Değerlendirmesi / Hızlı SOFA",
    "de_desc": "Sepsis-Klassifikation über 6 Organsysteme (Atmung, Gerinnung, Leber, Kreislauf, ZNS, Niere). qSOFA als Betten-Schnelltest: AF ≥ 22/min, GCS < 15, systolischer RR ≤ 100 mmHg.",
    "tr_desc": "Sepsis tanısında 6 organ sistemini (solunum, koagülasyon, karaciğer, dolaşım, nöroloji, böbrek) puanlayan skorlama.",
    "exam_pearl": "Sepsis = Infektion + akuter Anstieg des SOFA-Scores um ≥ 2 Punkte! Septischer Schock = Sepsis + Vasopressorenbedarf (MAP ≥ 65) + Laktat > 2 mmol/l trotz Volumen.",
    "exam_pearl_tr": "Sepsis = Enfeksiyon + SOFA skorunda >= 2 puan artış! Septik şok = Sepsis + vazopressör ihtiyacı (MAP >= 65) + sıvıya rağmen laktat > 2 mmol/L."
  },
  {
    "abbr": "ODS / CPM",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Osmotisches Demyelinisierungssyndrom / Zentrale pontine Myelinolyse",
    "tr_full": "Osmotik Demiyelinizasyon Sendromu (Santral Pontin Miyelinozis)",
    "de_desc": "Irreversible Schädigung der Myelinscheiden im Hirnstamm infolge zu rascher Korrektur einer chronischen Hyponatriämie (z. B. bei TURP-Syndrom).",
    "tr_desc": "Kronik hiponatreminin (örneğin TURP sendromunda) çok hızlı düzeltilmesiyle beyin sapında gelişen ve Locked-in sendromuna yol açan felç tablosu.",
    "exam_pearl": "⚠️ Striktes Tempolimit der Natriumkorrektur: Maximal 8–10 mmol/l in den ersten 24 Stunden (max. 18 mmol/l in 48 Stunden)!",
    "exam_pearl_tr": "⚠️ Kesin Sodyum Düzeltme Hız Sınırı: İlk 24 saatte EN FAZLA 8-10 mmol/L yükseltilebilir! Daha hızlısı ölümcül demiyelinizasyon yapar."
  },
  {
    "abbr": "TURP",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Transurethrale Resektion der Prostata (TURP-Syndrom)",
    "tr_full": "Transüretral Prostat Rezeksiyonu (TURP Sendromu)",
    "de_desc": "Endoskopische Prostata-OP mit Einschwemmung hypotoner Spülflüssigkeit (z. B. Glycin, Mannitol/Sorbitol) über eröffnete Venensinusse → Verdünnungshyponatriämie und Hypervolämie.",
    "tr_desc": "Prostat ameliyatında açılan venöz sinüslerden litrelerce hipotonik yıkama sıvısının emilmesiyle gelişen hipervolemik hiponatremi tablosu.",
    "exam_pearl": "Therapie bei Krampfanfall (Na < 120 mmol/l): OP sofort beenden! NaCl 3% (100 ml als Kurzinfusion über 10 Min), Schleifendiuretika (Furosemid), Sauerstoff/Intubation.",
    "exam_pearl_tr": "Nöbet gelişirse (Na < 120): Ameliyatı derhal durdur! NaCl %3 (100 ml 10 dakikada), Furosemid, havayolu güvenliği."
  },
  {
    "abbr": "ECMO",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Extrakorporale Membranoxygenierung",
    "tr_full": "Ekstrakorporeal Membran Oksijenasyonu (ECMO)",
    "de_desc": "Extrakorporales Lungen- oder Herz-Lungen-Unterstützungsverfahren: Veno-venös (VV-ECMO) bei refraktärem Lungenversagen (ARDS); Veno-arteriell (VA-ECMO) bei kardiogenem Schock.",
    "tr_desc": "Dirençli solunum veya dolaşım yetmezliğinde kanı vücut dışındaki oksijenatörden geçiren yaşam destek sistemi. VV-ECMO akciğer için, VA-ECMO kalp+akciğer için kullanılır.",
    "exam_pearl": "VV-ECMO: Reines Gasaustauschorgan (Oxygenierung & CO₂-Elimination), Herzfunktion muss intakt sein. VA-ECMO: Übernimmt auch die Kreislaufpumpfunktion.",
    "exam_pearl_tr": "VV-ECMO: Sadece gaz değişimi sağlar (kalp sağlam olmalı). VA-ECMO: Kalp pompasını da üstlenir (kardiyojenik şok)."
  },
  {
    "abbr": "ARDS",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Akutes Atemnotsyndrom (Acute Respiratory Distress Syndrome)",
    "tr_full": "Akut Solunum Sıkıntısı Sendromu (ARDS)",
    "de_desc": "Akute inflammatorische diffuse Lungenschädigung mit erhöhter Gefäßpermeabilität und nicht-kardiogenem Lungenödem. Berlin-Definition (Mild: Horovitz 201–300, Moderate: 101–200, Severe: ≤ 100 mmHg).",
    "tr_desc": "Enflamatuar non-kardiyojenik akciğer ödemi ve bilateral infiltratlarla karakterize ağır solunum yetmezliği. Berlin kriterleri (Horovitz oranı 201-300 hafif, 101-200 orta, <= 100 ağır).",
    "exam_pearl": "⚠️ Lungenprotektive Beatmung: Vt 6 ml/kg PBW (nicht Ist-Gewicht!), Pplat ≤ 30 cmH₂O, Driving Pressure ΔP < 14 cmH₂O, Bauchlagerung (Prone Positioning) bei PaO₂/FiO₂ < 150 mmHg für 16 h/Tag.",
    "exam_pearl_tr": "⚠️ Akciğer koruyucu ventilasyon: Vt 6 ml/kg İdeal Kilo, Pplato <= 30 cmH2O, Driving pressure < 14 cmH2O. Ağır ARDS'de (Horovitz < 150) günde 16 saat yüzüstü (prone) pozisyon!"
  },
  {
    "abbr": "TRALI",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Hämostase",
    "category_tr": "Acil, Reanimasyon & Hemostaz",
    "de_full": "Transfusion-Related Acute Lung Injury",
    "tr_full": "Transfüzyona Bağlı Akut Akciğer Hasarı",
    "de_desc": "Immunologisch vermitteltes nicht-kardiogenes Lungenödem innerhalb von 6 Stunden nach Transfusion zellulärer oder plasmatischer Blutprodukte (durch Leukozyten-Antikörper anti-HLA / anti-HNA im Spenderplasma).",
    "tr_desc": "Kan ürünü (özellikle plazma) transfüzyonundan sonraki ilk 6 saatte gelişen, donör antikorlarına bağlı non-kardiyojenik akciğer hasarı ve ağır hipoksemi.",
    "exam_pearl": "Klinik: Akute Dyspnoe, Hypoxämie, Fieber, Hypotonie, bilaterale Infiltrate, normales BNP / ZVD. Sofort Transfusion stoppen, Spender sperren, Meldung ans PEI (Paul-Ehrlich-Institut)!",
    "exam_pearl_tr": "Belirtiler: Ateş, hipotansiyon, hipoksemi, bilateral infiltrat (ZVD/BNP normal). Transfüzyonu derhal durdur, torbayı laboratuvara gönder, Paul-Ehrlich Enstitüsüne bildir."
  },
  {
    "abbr": "TACO",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Hämostase",
    "category_tr": "Acil, Reanimasyon & Hemostaz",
    "de_full": "Transfusion-Associated Circulatory Overload",
    "tr_full": "Transfüzyona Bağlı Dolaşım Aşırı Yüklenmesi",
    "de_desc": "Kardiogenes Lungenödem durch zu rasche oder übermäßige Transfusion von Flüssigkeit/Blutprodukten bei reduzierter kardialer Vorlast-Toleranz.",
    "tr_desc": "Kalp yetmezliği veya böbrek hastalarında hızlı kan transfüzyonuna bağlı gelişen hipervolemik kardiyojenik akciğer ödemi.",
    "exam_pearl": "Differenzierung zu TRALI: Bei TACO typisch Hypertonie, gestaute Halsvenen, erhöhtes BNP (> 1,5-facher Anstieg), gutes Ansprechen auf Furosemid und Nitrate!",
    "exam_pearl_tr": "TRALI'den farkı: TACO'da hipertansiyon, boyun ven dolgunluğu ve yüksek BNP vardır; Furosemid diürezine ve nitratlara hızla yanıt verir!"
  },
  {
    "abbr": "HIT II",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Hämostase",
    "category_tr": "Acil, Reanimasyon & Hemostaz",
    "de_full": "Heparin-induzierte Thrombozytopenie Typ II",
    "tr_full": "Heparine Bağlı Trombositopeni Tip 2",
    "de_desc": "Antikörper-vermittelte (PF4-Heparin-Komplex) lebensbedrohliche Thrombozytopenie mit exzessivem Thromboembolie-Risiko (arteriell und venös, 'White Clot Syndrome') an Tag 4–14 nach Heparingabe.",
    "tr_desc": "Heparin kullanımının 4-14. günlerinde antikorlarla trombositlerin kümelenmesi ve paradoxal ölümcül trombozlara (beyin, bacak, akciğer) yol açan immünolojik tablo.",
    "exam_pearl": "⚠️ Thrombozytenabfall um > 50%! KEINE Thrombozytenkonzentrate transfundieren! Heparin sofort absetzen und auf Argatroban oder Danaparoid umstellen!",
    "exam_pearl_tr": "⚠️ Trombositler %50'den fazla düşer! ASLA trombosit süspansiyonu verilmez (trombozu alevlendirir)! Heparin kesilir, Argatroban başlanır!"
  },
  {
    "abbr": "DIC",
    "category": "resuscitation",
    "category_de": "Notfall, Reanimation & Hämostase",
    "category_tr": "Acil, Reanimasyon & Hemostaz",
    "de_full": "Disseminierte intravasale Koagulopathie (Verbrauchskoagulopathie)",
    "tr_full": "Yaygın Damar İçi Pıhtılaşma (DIC)",
    "de_desc": "Systemische Aktivierung der Blutgerinnung mit mikrovaskulärer Fibrinablagerung (Multiorganversagen) und gleichzeitigem Verbrauch von Thrombozyten und Gerinnungsfaktoren (diffuse Blutung).",
    "tr_desc": "Mikrovasküler trombozlarla organ yetmezliği yaparken bir yandan da pıhtılaşma faktörlerini tüketerek masif kanamaya yol açan ölümcül tükenme koagülopatisi.",
    "exam_pearl": "Labor: Thrombozytopenie, Fibrinogensturz (< 1,5 g/l), D-Dimere exzessiv erhöht, Quick stark erniedrigt, aPTT verlängert. Therapie: Grunderkrankung behandeln + zielgerichtete Substitution (Fibrinogen, PPSB, TK).",
    "exam_pearl_tr": "Laboratuvar: Trombosit ve fibrinojen dip yapar, D-Dimer uçar, aPTT uzar. Tedavi: Altta yatan nedeni yok et + Fibrinojen ve faktör replasmanı yap."
  },
  {
    "abbr": "Horner-Syndrom",
    "category": "neuro_reg",
    "category_de": "Neuroanästhesie & Regionalanästhesie",
    "category_tr": "Nöroanestezi & Rejyonel Anestezi",
    "de_full": "Horner-Trias (Sympathikusblockade am Ganglion stellatum)",
    "tr_full": "Horner Sendromu Triadı",
    "de_desc": "Lähmung des zervikalen Grenzstrangs / Ganglion stellatum bei interskalenärer Plexusblockade (ISB) oder Epiduralanästhesie hoch thorakal.",
    "tr_desc": "İnterskalen blok veya yüksek torakal epidural sonrasında servikal sempatik zincirin (stellat ganglion) geçici felci sonucu gelişen göz bulguları.",
    "exam_pearl": "Klassische Trias: Ptosis (Herabhängen des Oberlids), Miosis (Pupillenverengung), Enophthalmus (Zurückweichen des Augapfels) + ipsilaterale Anhidrose und Rötung. Vorab aufklären!",
    "exam_pearl_tr": "Klasik Triad: Pitozis (göz kapağı düşüklüğü), Miyozis (göz bebeği küçülmesi), Enoftalmus (göz küresinin çökmesi) + aynı tarafta terleme kaybı ve kızarıklık. Geçicidir, hastaya önceden anlatılmalıdır."
  },
  {
    "abbr": "ASA-PS",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "ASA Physical Status Classification",
    "tr_full": "ASA Fiziksel Durum Sınıflaması",
    "de_desc": "Sechsstufige Risikoklassifikation der American Society of Anesthesiologists zur Einschätzung des perioperativen Allgemeinzustands des Patienten.",
    "tr_desc": "Hastanın ameliyat öncesi sistemik sağlık durumunu ve operatif riskini belirleyen 6 basamaklı uluslararası skorlama.",
    "exam_pearl": "ASA I: gesund | ASA II: leichte Systemerkrankung ohne Leistungseinschränkung | ASA III: schwere Systemerkrankung mit Leistungseinschränkung | ASA IV: ständige Lebensbedrohung | ASA V: moribund | ASA VI: hirntot (Organspende). Notfälle: Suffix 'E'!",
    "exam_pearl_tr": "ASA I: Sağlıklı | ASA II: Hafif sistemik hastalık | ASA III: Günlük hayatı kısıtlayan ağır hastalık | ASA IV: Sürekli hayati tehdit | ASA V: Ameliyatsız 24 saat yaşayamayacak hasta | ASA VI: Beyin ölümü. Acillerde yanına 'E' eklenir."
  },
  {
    "abbr": "Cormack-Lehane",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "Cormack & Lehane Laryngoskopie-Klassifikation",
    "tr_full": "Cormack-Lehane Laringoskopi Sınıflaması",
    "de_desc": "Gradeinteilung der Sichtbarkeit der Glottis während der direkten Laryngoskopie zur Dokumentation des Intubationsbefunds.",
    "tr_desc": "Direkt laringoskopi sırasında glottik yapıların ve vokal kordların görünürlük derecesini belirleyen 4 evreli sınıflama.",
    "exam_pearl": "Grad I: Vollständige Stimmritze sichtbar | Grad II: Nur hintere Kommissur sichtbar | Grad III: Nur Epiglottis sichtbar (keine Stimmritze) | Grad IV: Weder Stimmritze noch Epiglottis sichtbar (nur weicher Gaumen). Grad III/IV = schwierige Intubation!",
    "exam_pearl_tr": "Evre 1: Kordlar tam görünür | Evre 2: Sadece arka komissür | Evre 3: Sadece epiglottis ucu görünür, kordlar yok | Evre 4: Epiglottis bile görünmez. Evre 3 ve 4 zor entübasyondur!"
  },
  {
    "abbr": "STOP-Bang",
    "category": "airway",
    "category_de": "Atemwegsmanagement & Beatmung",
    "category_tr": "Havayolu Yönetimi & Ventilasyon",
    "de_full": "STOP-Bang Questionnaire (Obstruktives Schlafapnoe-Syndrom, OSAS)",
    "tr_full": "STOP-Bang OSAS Risk Anketi",
    "de_desc": "Achtstufiger Screening-Fragebogen zur Detektion eines obstruktiven Schlafapnoe-Syndroms in der Prämedikationsvisite.",
    "tr_desc": "Preoperatif vizitte uyku apnesi (OSAS) riskini ve postoperatif solunum depresyonu yatkınlığını belirleyen 8 parametreli tarama testi.",
    "exam_pearl": "S: Snoring (Schnarchen), T: Tired (Tagesmüdigkeit), O: Observed apnea, P: Blood Pressure (Hypertonie), B: BMI > 35 kg/m², A: Age > 50 J, N: Neck circumference > 40 cm, G: Gender (männlich). Score ≥ 5 = hohes OSAS-Risiko!",
    "exam_pearl_tr": "Parametreler: Horlama, Gündüz yorgunluğu, Gözlenen apne, Hipertansiyon, BMI > 35, Yaş > 50, Boyun çevresi > 40 cm, Erkek cinsiyet. Puan >= 5: Ağır OSAS ve postop opioid duyarlılığı riski!"
  },
  {
    "abbr": "APGAR",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "APGAR-Score für Neugeborene",
    "tr_full": "Yenidoğan APGAR Skoru",
    "de_desc": "Standardisierte Beurteilung der postnatalen Vitalität und Adaptation des Neugeborenen nach 1, 5 und 10 Minuten.",
    "tr_desc": "Doğumdan sonra 1, 5 ve 10. dakikalarda bebeğin yaşamsal uyumunu değerlendiren 10 puanlık standart skor.",
    "exam_pearl": "A: Aussehen (Hautfarbe rosig/blau), P: Puls (HF > 100/min), G: Grimassieren (Reflexe), A: Aktivität (Muskeltonus), R: Respiration (kräftiges Schreien). Normal: 8–10 Punkte. Notfallreanimation bei < 4 Punkten!",
    "exam_pearl_tr": "A: Görünüm (Renk), P: Nabız (>100), G: Grimres (Uyarıya yanıt), A: Aktivite (Kas tonusu), R: Solunum (Ağlama). 8-10 normal. < 4 puan acil neonatal resüsitasyon gerektirir!"
  },
  {
    "abbr": "IABP",
    "category": "hemodynamics",
    "category_de": "Kardiovaskulär & Hämodynamik",
    "category_tr": "Kardiyovasküler & Hemodinamik",
    "de_full": "Intraaortale Ballonpumpe",
    "tr_full": "İntra-Aortik Balon Pompası (IABP)",
    "de_desc": "Mechanisches Kreislaufunterstützungssystem in der Aorta descendens zur Nachlastsenkung und Steigerung der Koronarperfusion.",
    "tr_desc": "İnen torasik aortaya yerleştirilen, diyastolde şişerek koroner kan akımını artıran, sistolde inerek sol ventrikül artı yükünü azaltan mekanik destek cihazı.",
    "exam_pearl": "⚠️ Kontraindikation: Aortenklappeninsuffizienz (verstärkt den Regurgitationsjet!) und Aortendissektion!",
    "exam_pearl_tr": "⚠️ Kesin Kontrendikasyon: Aort kapak yetmezliği (yetmezlik akımını artırır) ve aort diseksiyonu!"
  },
  {
    "abbr": "CVVHDF",
    "category": "peds_obs",
    "category_de": "Pädiatrie, Geburtshilfe & Intensiv",
    "category_tr": "Pediyatri, Doğum & Yoğun Bakım",
    "de_full": "Kontinuierliche veno-venöse Hämodiafiltration",
    "tr_full": "Sürekli Veno-Venöz Hemodiyafiltrasyon (CRRT)",
    "de_desc": "Kontinuierliches Nierenersatzverfahren (CRRT) auf Intensivstationen, das Diffusion (Dialyse) und Konvektion (Filtration) kombiniert. Schont den instabilen Kreislauf.",
    "tr_desc": "Hemodinamik olarak anstabil yoğun bakım hastalarında diyaliz ve filtrasyonu birleştirerek yavaş ve güvenli sıvı/toksin temizliği sağlayan sürekli diyaliz yöntemi.",
    "exam_pearl": "Regionale Zitratantikoagulation (RCA) ist Goldstandard: Chelatiert Calcium im Filterkreis, systemische Re-Infusion von CaCl₂. Vorsicht vor Zitratakkumulation (Gesamt-Ca/ionisiertes Ca > 2,5)!",
    "exam_pearl_tr": "Bölgesel Sitrat Antikoagülasyonu altın standarttır. Filtrede kalsiyumu bağlar, hastaya verilmeden kalsiyum infüze edilir. Sitrat birikimi (Total Ca / İyonize Ca > 2.5) toksisite işaretidir!"
  }
];

  // Global export
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = ANESTHESIA_ABBREVIATIONS;
  }
  global.ANESTHESIA_ABBREVIATIONS = ANESTHESIA_ABBREVIATIONS;
})(typeof window !== 'undefined' ? window : this);
