const fs = require('fs');
const path = require('path');

const NEW_AMBOSS_QUESTIONS = [
  {
    "id": "q_amboss_01",
    "category": "Palliativmedizin & Ethik",
    "amboss_pillar": "schmerz",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Ein 78-jähriger Patient mit metastasiertem Pankreaskarzinom erleidet postoperativ nach Hemikolektomie eine Peritonitis durch Anastomoseninsuffizienz. Auf der Intensivstation besteht ein katecholaminrefraktärer septischer Schock (Noradrenalin 0,6 µg/kg/min, Vasopressin), schweres ARDS und akutes Nierenversagen unter CVVHD (Laktat 9,2 mmol/l, Multiorganversagen). Es liegt eine schriftliche Patientenverfügung vor, die lebensverlängernde Maßnahmen bei infauster Prognose ablehnt. Die Ehefrau ist als Vorsorgebevollmächtigte anwesend.\n1. Wie definieren Sie die rechtlichen und ethischen Kriterien für eine Therapiezieländerung (Begrenzung/Beendigung lebensverlängernder Maßnahmen nach BÄK-Grundsätzen)?\n2. Wie binden Sie die Patientenverfügung und die Vorsorgebevollmächtigte rechtssicher ein?\n3. Welche Maßnahmen werden deeskaliert bzw. beendet, und welche palliativen Maßnahmen müssen zwingend aufrechterhalten bzw. intensiviert werden?",
    "question_tr": "Metastatik pankreas kanseri olan 78 yaşında bir hastada hemikolektomi sonrası anastomoz kaçağına bağlı peritonit gelişir. Yoğun bakımda vazopressöre dirençli septik şok (Noradrenalin 0,6 µg/kg/dk, Vazopressin), ağır ARDS ve CVVHD altında akut böbrek yetmezliği tablosu mevcuttur (Laktat 9,2 mmol/L, multiorgan yetmezliği). Hastanın prognozun geri dönüşsüz olduğu durumlarda hayatı uzatıcı tedavileri reddeden yazılı bir hasta vasiyeti (Patientenverfügung) bulunmaktadır. Eşi yasal sağlık vekili (Vorsorgebevollmächtigte) olarak hazır bulunmaktadır.\n1. Alman Tabipler Birliği (BÄK) ilkelerine göre tedavi hedefinin değiştirilmesi (yaşam destekleyici tedavilerin kısıtlanması/sonlandırılması) için hukuki ve etik kriterleri nasıl tanımlarsınız?\n2. Hasta vasiyetini ve yasal vekili hukuki güvenceyle sürece nasıl dahil edersiniz?\n3. Hangi tedaviler sonlandırılır/deeskale edilir ve hangi palyatif bakım önlemleri mutlaka sürdürülmeli veya yoğunlaştırılmalıdır?",
    "answer_de": "1. RECHTLICHE & ETHISCHE KRITERIEN FÜR DIE THERAPIEZIELÄNDERUNG (BÄK-GRUNDSÄTZE):\n• Indikationsverlust: Wenn eine medizinische Behandlung das Überleben nicht mehr sichern kann, das Multiorganversagen irreversibel ist und das Behandlungsziel (Wiederherstellung von Lebensqualität) unerreichbar ist, erlischt die Indikation für invasive Maximaltherapie.\n• Patientenautonomie (§ 1901a BGB): Eine medizinische Behandlung darf nur mit Einwilligung des Patienten erfolgen. Widerspricht sie dem Willen des Patienten, ist sie rechtlich eine Körperverletzung und muss unterbleiben!\n• Ethische Abgrenzung: Das Unterlassen, Begrenzen oder Beenden nicht mehr indizierter lebensverlängernder Maßnahmen (Passive Sterbehilfe / Therapiezieländerung) ist rechtlich geboten und ethisch Pflicht. Sie ist strikt abzugrenzen von der strafbaren aktiven Sterbehilfe (Tötung auf Verlangen, § 216 StGB).\n\n2. RECHTSSICHERE EINBINDUNG VON PATIENTENVERFÜGUNG & BEVOLLMÄCHTIGTER:\n• Verbindlichkeit der Patientenverfügung: Liegt eine schriftliche, wirksame Patientenverfügung vor, die auf die konkrete Behandlungssituation zutrifft, ist sie für Ärzte und Vertreter unmittelbar verbindlich!\n• Rolle der Vorsorgebevollmächtigten: Die Bevollmächtigte entscheidet nicht nach ihrem eigenen Willen, sondern hat als Sachwalterin den niedergelegten oder mutmaßlichen Willen des Patienten zur Geltung zu bringen.\n• Interdisziplinäres Konsensgespräch: Gemeinsame ethische Fallbesprechung im Team (Ärzte, Pflege) und strukturiertes Gespräch mit der Bevollmächtigten. Lückenlose Dokumentation der Therapiezieländerung (DNR/DNI) und der Begründung in der Patientenakte.\n\n3. DURCHFÜHRUNG DER DEESKALATION & PALLIATIVE BEGLEITUNG:\n• Zu beendende / nicht zu eskalierende Maßnahmen: Keine Reanimation (DNR), keine Defibrillation, keine Re-Intubation, Beendigung der Nierenersatztherapie (CVVHD stoppen), stufenweises Ausschleichen von Katecholaminen, keine invasiven Blutentnahmen oder diagnostischen Transporte.\n• ZWINGEND ZU INTENSIVIERENDE PALLIATIVE SYMPTOMKONTROLLE:\n - Schmerztherapie & Dyspnoelinderung: MORPHIN kontinuierlich über Perfusor (z.B. 2–5 mg/h i.v., bedarfsorientiert titriert).\n - Anxiolyse & Sedierung: MIDAZOLAM (1–3 mg/h i.v.) zur Linderung von Todesangst und Unruhe.\n - Sekretionshemmung: Butylscopolamin bei Rasselatmung.\n - Basis-Pflege: Mundpflege, Befeuchtung, Dekubitusprophylaxe, bequeme Lagerung, Ermöglichung des Abschieds durch Angehörige ohne Zeitdruck.",
    "answer_tr": "1. TEDAVİ HEDEFİ DEĞİŞİKLİĞİNİN HUKUKİ VE ETİK KRİTERLERİ (BÄK İLKELERİ):\n• Endikasyon Kaybı: Tıbbi tedaviler artık hastanın yaşamını kurtaramıyor, multiorgan yetmezliği geri döndürülemez aşamaya gelmiş ve tedavi hedefi ulaşılamaz hale gelmişse invaziv tedavinin tıbbi endikasyonu ortadan kalkar.\n• Hasta Özerkliği (Alman Medeni Kanunu § 1901a BGB): Tıbbi müdahale ancak hastanın rızasıyla yapılabilir. Hastanın iradesine aykırı tedavi sürdürmek hukuken müessir fiildir (Körperverletzung) ve durdurulmalıdır.\n• Etik Ayrım: Endikasyonsuz hayatı uzatıcı tedavilerin sonlandırılması (pasif ötenazi / tedavi hedefi değişimi) hekimin yasal ve etik görevidir. Bu durum, TCK kapsamında suç olan aktif ötenaziden (talep üzerine öldürme, § 216 StGB) kesinlikle farklıdır.\n\n2. HASTA VASİYETİ VE VEKİLİN SÜRECE DAHİL EDİLMESİ:\n• Hasta Vasiyetinin Bağlayıcılığı: Somut klinik durumu kapsayan yazılı bir hasta vasiyeti hekimler ve vekiller için doğrudan bağlayıcıdır.\n• Sağlık Vekilinin Rolü: Vekil kendi isteğine göre değil, hastanın beyan ettiği veya muhtemel iradesine tercüman olarak karar verir.\n• Ortak Konsensus: Ekip içi etik vaka değerlendirmesi, aile ile şeffaf görüşme ve tüm kararların (DNR/DNI) gerekçeleriyle dosyaya eksiksiz kaydedilmesi.\n\n3. DEESKALASYON VE PALYATİF BAKIM PROTOKOLÜ:\n• Sonlandırılacak Tedaviler: Resüsitasyon yapılmaması (DNR), CVVHD diyalizinin kapatılması, katekolaminlerin kademeli kesilmesi, gereksiz kan gazı/kan alma ve tetkiklerin durdurulması.\n• ZORUNLU OLARAK YOĞUNLAŞTIRILACAK PALYATİF ÖNLEMLER:\n - Ağrı ve Dispne Kontrolü: Sürekli MORFİN perfüzörü (2-5 mg/saat İ.V., semptoma göre titre).\n - Anksiyoliz ve Sedasyon: MİDAZOLAM (1-3 mg/saat İ.V.) ile nefes darlığı paniği ve ajitasyonun önlenmesi.\n - Sekresyon Kontrolü: Hırıltılı solunum için Butilskopolamin.\n - Temel Bakım: Ağız bakımı, rahatlatıcı pozisyon, ailenin kısıtlamasız hastanın yanında kalabilmesi.",
    "examiner_tip": "Düsseldorfer Ethik- & Intensiv-Klassiker: 'Ein Patient verstirbt auf Ihrer Intensivstation – wann dürfen Sie Therapien beenden?' K.O.-Kriterium: Wer den Unterschied zwischen Beendigung nicht mehr indizierter Maßnahmen (erlaubt & geboten) und aktiver Tötung (strafbar nach § 216 StGB) nicht kennt oder den Patienten unter Schmerzen ersticken lässt, fällt sofort durch! Symptomkontrolle mit Morphin & Midazolam muss aktiv intensiviert werden!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Düsseldorf Etik & Yoğun Bakım Klasiği: 'Yoğun bakımda tedaviyi ne zaman kesebilirsiniz?' K.O. Kriteri: Endikasyonsuz tedavinin sonlandırılması ile aktif ötenazi arasındaki farkı bilmeyen veya palyatif süreçte hastayı ağrı ve nefes darlığı içinde bırakan aday anında kalır! Morfin ve Midazolam ile semptom kontrolü kesilmez, aksine artırılır!"
  },
  {
    "id": "q_amboss_02",
    "category": "Palliativmedizin & Ethik",
    "amboss_pillar": "schmerz",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Eine 68-jährige Patientin mit therapierefraktärer terminaler Lungenfibrose im Sterbeprozess leidet unter quälender Atemnot (Ruhedyspnoe), Panikattacken und beginnender terminaler Rasselatmung. Sauerstoff über High-Flow lindert die subjektive Atemnot nicht mehr; die Patientin äußert Todesangst ('Ich ersticke!').\n1. Welches ist das pharmakologische Mittel der 1. Wahl zur Linderung der therapierefraktären Ruhedyspnoe und wie lautet der Wirkmechanismus?\n2. Wann ist eine palliative Sedierung indiziert, welche Substanzen werden eingesetzt und wie grenzen Sie diese ethisch-rechtlich von einer Tötung auf Verlangen ab?\n3. Wie behandeln Sie die terminale Rasselatmung (Todesröcheln) leitliniengerecht?",
    "question_tr": "Son dönem akciğer fibrozu olan 68 yaşında bir hasta, ölüm sürecinde dayanılmaz istirahat dispnesi, panik ataklar ve hırıltılı ölüm solunumu (terminal rasselatmung) yaşamaktadır. Yüksek akımlı oksijen hastanın nefes darlığı hissini hafifletmemektedir; hasta 'Boğuluyorum!' diyerek ölüm korkusu yaşamaktadır.\n1. Tedaviye dirençli istirahat dispnesinde 1. tercih farmakolojik ajan hangisidir ve etki mekanizması nedir?\n2. Palyatif sedasyon hangi durumlarda endikedir, hangi ilaçlar kullanılır ve bu işlem talep üzerine öldürmeden etik-hukuki olarak nasıl ayrılır?\n3. Terminal hırıltılı solunumu (ölüm hırıltısı) kılavuzlara göre nasıl tedavi edersiniz?",
    "answer_de": "1. MITTEL DER 1. WAHL BEI TERMINALER DYSPNOE:\n• Substanz: MORPHIN (oder ein anderes starkes Opioid, z.B. Fentanyl, Hydromorphon).\n• Wirkmechanismus: Morphin senkt die Empfindlichkeit des bulbären Atemzentrums für Hyperkapnie und Hypoxie, dämpft das subjektive Erstickungsgefühl im limbischen System, senkt die Atemfrequenz, reduziert den Sauerstoffverbrauch der Atemmuskulatur und senkt über Vasodilatation die pulmonale Vorlast.\n• Dosierung: Bei Opioid-naiven Patienten initial 2,5–5 mg Morphin langsam i.v. titriert (oder 5–10 mg s.c./oral), gefolgt von einer kontinuierlichen Infusion (z.B. 1–2 mg/h i.v.).\n• K.O.-KRITERIUM: Die Vorenthaltung von Opioiden aus unbegründeter Angst vor Atemdepression bei sterbenden Patienten mit Erstickungsangst ist ein gravierender Behandlungsfehler!\n\n2. PALLIATIVE SEDIERUNG:\n• Indikation: Ausschließlich bei THERAPIEREFRAKTÄREN, UNERTRÄGLICHEN SYMPTOMEN (z.B. Erstickungsnot, massive Schmerzen, therapierefraktäres Delir mit Angst) im unmittelbaren Sterbeprozess, wenn alle spezifischen Maßnahmen versagt haben.\n• Substanzen: MIDAZOLAM als Mittel der 1. Wahl (Bolus 1–5 mg s.c./i.v., dann 0,5–2 mg/h Perfusor); Alternativen: Levomepromazin (Neuroleptikum bei Delir/Übelkeit) oder Propofol.\n• Ethisch-rechtliche Abgrenzung (Prinzip der Doppelwirkung): Das primäre und intendierte Behandlungsziel ist die Linderung des unerträglichen Leidens durch Bewusstseinsdämpfung. Eine eventuelle Verkürzung der Überlebenszeit wird als unbeabsichtigte, unvermeidbare Nebenwirkung in Kauf genommen. Bei Tötung auf Verlangen ist der Tod das primäre Handlungsziel (strafbar!).\n\n3. BEHANDLUNG DER TERMINALEN RASSELATMUNG (DEATH RATTLE):\n• Pathophysiologie: Sekretansammlung im Pharynx und Larynx bei erloschenem Schluck- und Hustenreflex.\n• Medikamentös: Frühzeitiger Einsatz von Anticholinergika zur Hemmung der Neusekretion: BUTYLSCOPOLAMIN (20 mg s.c./i.v. alle 4–6 h oder kontinuierlich 60–120 mg/24h) oder Glycopyrroniumbromid (0,2–0,4 mg s.c./i.v.).\n• Nicht-medikamentös: Oberkörperhochlagerung (30°), vorsichtige Seitenlagerung zur passiven Drainage des Sekrets.\n• KARDINALFEHLER: Niemals tiefes endotracheales Absaugen durchführen! Dies führt zu Schleimhauttraumata, Vagusreizung und löst Panik und Würgereiz beim Sterbenden aus!",
    "answer_tr": "1. TERMİNAL DİSPNEDE 1. TERCİH İLAÇ:\n• İlaç: MORFİN (veya Fentanil, Hidromorfon gibi güçlü bir opioid).\n• Etki Mekanizması: Morfin beyin sapındaki solunum merkezinin hiperkapni duyarlılığını azaltır, limbik sistemdeki boğulma korkusunu dindirir, solunum işini ve oksijen tüketimini düşürür, pulmoner ön yükü azaltır.\n• Doz: Opioid almamış hastada 2,5-5 mg İ.V. yavaş titrasyon (veya 5 mg s.c.), ardından sürekli infüzyon (1-2 mg/saat İ.V.).\n• K.O. KRİTERİ: Ölüm sürecindeki nefes darlığı çeken hastaya 'solunumu baskılar' korkusuyla morfin vermemek ağır bir hekimlik hatasıdır!\n\n2. PALYATİF SEDASYON:\n• Endikasyon: Sadece tüm palyatif tedavilere DİRENÇLİ, KATLANILAMAZ SEMPTOMLAR (boğulma hissi, ajitasyon, masif ağrı) varlığında.\n• İlaçlar: İlk tercih MİDAZOLAM (1-5 mg İ.V./s.c. bolus, ardından 0,5-2 mg/saat infüzyon). Alternatif: Levomepromazin veya Propofol.\n• Etik ve Hukuki Ayrım (Çift Etki İlkesi): Amaç yaşamı sonlandırmak değil, bilinci hafifleterek dayanılmaz acıyı dindirmektir. Ölümün kısalması istenmeyen ikincil bir sonuç olarak kabul edilir (Aktif ötenazide ise amaç doğrudan ölümdür ve suçtur).\n\n3. TERMİNAL HIRILTILI SOLUNUMUN TEDAVİSİ:\n• İlaç: Tükürük ve sekresyon üretimini durdurmak için antikolinerjikler: BUTİLSKOPOLAMİN (20 mg s.c./İ.V. 4-6 saatte bir) veya Glikopirolat.\n• Pozisyon: Baş-gövde 30° yüksekte, sekresyonun kendiliğinden akması için hafif yan pozisyon.\n• VAHİM HATA: Ölüm sürecindeki hastayı asla derin trakeal aspirasyona zorlamayın! Bu işlem kanama, refleks spazm ve panik yaratır!",
    "examiner_tip": "Prüferfrage: 'Geben Sie einem sterbenden Patienten mit schwerer Atemnot Morphin, obwohl der pCO2 bereits 55 mmHg beträgt?' Richtige Antwort: Ja, unbedingt! Morphin ist das stärkste Medikament gegen Atemnot. Die Linderung des Erstickungstodes hat oberste Priorität (Prinzip der Doppelwirkung). Anticholinergika bei Rasselatmung frühzeitig verabreichen, kein invasives Absaugen!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jüri sorusu: 'Terminal dispnedeki hastaya pCO2 55 mmHg olsa bile morfin verir misiniz?' Doğru cevap: Evet, kesinlikle! Morfin nefes darlığının 1 numaralı ilacıdır. Ölüm anındaki boğulma ıstırabını dindirmek her şeyden önce gelir. Hırıltıda Butilskopolamin verilir, asla derin aspirasyon yapılmaz!"
  },
  {
    "id": "q_amboss_03",
    "category": "Geriatrie & Delirmanagement",
    "amboss_pillar": "intensiv",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Eine 82-jährige Patientin (Z.n. operierter Oberschenkelhalsfraktur) wird am 2. postoperativen Tag auf der Station zunehmend apathisch, verlangsamt, desorientiert und verweigert die Nahrungs- und Flüssigkeitseinnahme. Die Pflegekraft meldet bei der Visite: 'Die Patientin schläft nur noch und ist glücklicherweise ganz friedlich.'\n1. Welche Form des postoperativen Delirs (POD) liegt hier vor und warum birgt diese Form die höchste Letalität?\n2. Mit welchem validierten Screening-Score stellen Sie die Diagnose auf Normalstation vs. Intensivstation?\n3. Wie lautet Ihr multimodales Sofortmanagement (Ausschluss somatischer Trigger, nicht-medikamentöse Maßnahmen, medikamentöse Therapie) und welche Medikamente sind strikt kontraindiziert?",
    "question_tr": "Kalça kırığı ameliyatı geçiren 82 yaşında bir kadın hasta, postoperatif 2. günde serviste giderek apatikleşir, yavaşlar, oryantasyonu bozulur, yeme ve içmeyi reddeder. Servis hemşiresi vizitte: 'Hasta bütün gün uyuyor, neyse ki çok uslu ve sakin' demektedir.\n1. Burada postoperatif deliryumun (POD) hangi formu söz konusudur ve bu form neden en yüksek mortaliteye sahiptir?\n2. Serviste ve yoğun bakımda tanıyı hangi geçerliliği kanıtlanmış skorlama araçlarıyla koyarsınız?\n3. Çok yönlü acil yönetiminiz (somatik tetikleyicilerin taranması, ilaç dışı önlemler, ilaç tedavisi) nasıldır ve hangi ilaçlar kesinlikle kontrendikedir?",
    "answer_de": "1. DELIRFORM & PROGNOSTISCHE RELEVANZ:\n• Form: HYPOAKTIVES DELIR (macht ca. 50–60% aller Delirien im Alter aus).\n• Gefährlichkeit: Es wird häufig übersehen oder als 'Altersmüdigkeit/Depression' fehlinterpretiert, weil die Patienten nicht agitiert oder laut sind. Das hypoaktive Delir hat die HÖCHSTE MORTALITÄT aller Delirformen infolge von Aspiration, Dehydratation, Immobilität und verpassten somatischen Komplikationen!\n\n2. VALIDIERTE SCREENING-INSTRUMENTE:\n• Auf Normalstation: CAM (Confusion Assessment Method) oder 4AT.\n• Auf Intensivstation: CAM-ICU oder ICDSC (Intensive Care Delirium Screening Checklist).\n• Die 4 CAM-Kriterien: 1. Akuter Beginn und fluktuierender Verlauf + 2. Inaufmerksamkeit (Buchstabieren von ANANAS rückwärts) PLUS entweder 3. Desorganisiertes Denken ODER 4. Alteriertes Bewusstseinsniveau (Lethargie/Stupor).\n\n3. MULTIMODALES MANAGEMENT & KONTRAINDIKATIONEN:\n• 1. Somatische Ursachensuche (DELIR-Mnemonic):\n - D: Drugs (Anticholinergika absetzen, Opioidüberhang?)\n - E: Elektrolyte & Dehydratation (Na, K, Ca, Harnstoff/Kreatinin)\n - L: Lunge & Infektion (Pneumonie, Harnwegsinfekt, Sepsis, CRP?)\n - I: Ischämie & Hypoxie (BGA, EKG, SpO2)\n - R: Retention (Harnverhalt mit Überlaufblase? Obstipation/Koprostase?) & Pain (Schmerztherapie unzureichend?)\n• 2. Nicht-medikamentöse Basismassnahmen (Grundpfeiler!):\n - Brille und Hörgeräte sofort anpassen!\n - Reorientierung (Uhr, Kalender, Tag-Nacht-Rhythmus, Fensterlicht).\n - Frühe Remobilisation, ausreichende Hydrierung, vertraute Bezugspersonen am Bett.\n• 3. Medikamentöse Therapie (nur bei Eigen-/Fremdgefährdung oder Halluzinationen):\n - Mittel der Wahl: Niedrig dosierte hochpotente Antipsychotika (Haloperidol 0,5–1 mg p.o./i.v., Melperon oder Pipamperon bei älteren Patienten).\n - Auf Intensivstation: DEXMEDETOMIDIN (Alpha-2-Agonist) zur Erhaltung der Kooperationsfähigkeit ohne Atemdepression.\n• KONTRAINDIZIERTE MEDIKAMENTE (K.O.-KRITERIUM):\n - BENZODIAZEPINE (Lorazepam, Diazepam etc.) sind streng kontraindiziert! Sie triggern und verschlimmern das Delir massiv (paradoxe Reaktion, Sturzgefahr, ZNS-Dämpfung). Einzige Ausnahme: Alkoholentzugsdelir!\n - Anticholinerge Substanzen (z.B. Atropin, Scopolamin, Diphenhydramin) meiden (Priscus-Liste).",
    "answer_tr": "1. DELİRYUM FORMU VE ÖNEMİ:\n• Form: HİPOAKTİF DELİRYUM (yaşlılarda deliryum vakalarının %50-60'ını oluşturur).\n• Klinik Tehlike: Hasta sessiz ve sakin uyuduğu için hekimler ve hemşireler tarafından 'yorgunluk/depresyon' sanılarak sıklıkla atlanır. Ancak hipoaktif deliryum aspirasyon, beslenme yetersizliği ve hareketsizliğe bağlı EN YÜKSEK ÖLÜM ORANINA sahiptir!\n\n2. GEÇERLİ SKORLAMA ARAÇLARI:\n• Serviste: CAM (Confusion Assessment Method) veya 4AT.\n• Yoğun Bakımda: CAM-ICU veya ICDSC.\n• CAM 4 Ana Kriteri: 1. Akut başlangıç ve dalgalı seyir + 2. Dikkat dağınıklığı + (3. Dağınık düşünce VEYA 4. Değişmiş bilinç düzeyi/letarji).\n\n3. YÖNETİM VE KONTRENDİKASYONLAR:\n• Somatik Nedenleri Tara (DELIR kuralı): İlaçlar (antikolinerjikler?), Elektrolit/dehidrasyon, Enfeksiyon (idrar yolu/akciğer), İskemi/hipoksi, Retansiyon (glob vezikale/idrar yapamama, kabızlık) ve Ağrı!\n• İlaç Dışı Temel Önlemler (En Etkili Adım): Gözlük ve işitme cihazını hemen takın! Zaman oryantasyonu (saat, takvim, gündüz ışığı), erken mobilizasyon, tanıdık aile bireyleri.\n• İlaç Tedavisi (Sadece gerektiğinde): Düşük doz Haloperidol (0,5-1 mg) veya Pipamperon/Melperon. Yoğun bakımda Deksmedetomidin.\n• KESİNLİKLE KONTRENDİKE İLAÇLAR (K.O. KRİTERİ):\n - BENZODİYAZEPİNLER (Lorazepam vb.) kesinlikle yasaktır! Yaşlıda deliryumu fırlatır ve paradoksal ajitasyon yapar (tek istisna: alkol yoksunluğu deliryumu).\n - Antikolinerjik ilaçlardan kaçınılmalıdır (Priscus listesi).",
    "examiner_tip": "Düsseldorfer Geriatrie-Klassiker: 'Die 85-jährige Patientin schläft nach Hüft-OP friedlich – alles in Ordnung?' K.O.-Kriterium: Nein, hochgradiger Verdacht auf hypoaktives Delir! CAM-ICU anwenden, Harnverhalt/Schmerzen/Infekt ausschließen, Brille/Hörgerät anpassen. Niemals Benzodiazepine zur Delirtherapie geben!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jüri tuzağı: 'Kalça ameliyatı sonrası 85 yaşındaki teyze mışıl mışıl uyuyor, her şey yolunda mı?' K.O. Kriteri: Hayır, hipoaktif deliryum şüphesi! CAM testi yap, idrar sondasını kontrol et, ağrıyı kes, gözlüğü tak. Asla uyusun diye benzodiazepin verme!"
  },
  {
    "id": "q_amboss_04",
    "category": "Geriatrie & Delirmanagement",
    "amboss_pillar": "anaesthesie",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Ein 86-jähriger multimorbider Patient (KHK mit Stent vor 3 Jahren, CKD Stadium 3b mit eGFR 36 ml/min, Polypharmazie mit 8 Dauermedikamenten, Frailty-Score 5) erleidet im Pflegeheim eine dislozierte Schenkelhalsfraktur. Der Unfallchirurg meldet eine Duokopf-Hemiprothese an und fordert eine OP-Freigabe innerhalb von 24 Stunden.\n1. Warum fordert die DGAI/AWMF-Leitlinie eine operative Versorgung von Schenkelhalsfrakturen zwingend innerhalb von 24 Stunden?\n2. Wie wägen Sie Allgemeinanästhesie vs. Spinalanästhesie beim geriatrischen Frailty-Patienten evidenzbasiert ab?\n3. Welches ultraschallgestützte Regionalanästhesieverfahren eignet sich zur perioperativen Schmerztherapie ohne motorische Schwäche und welche Prinzipien der Narkoseführung müssen beachtet werden?",
    "question_tr": "Çoklu ek hastalığı olan 86 yaşında bir hasta (3 yıl önce stentli KHK, evre 3b KBY eGFR 36 ml/dk, 8 kronik ilaç, Kırılganlık/Frailty skoru 5) bakım evinde düşerek kalça kırığı geçirir. Ortopedist parsiyel protez planlamakta ve 24 saat içinde ameliyat için anestezi onayı istemektedir.\n1. DGAI ve AWMF kılavuzları kalça kırıklarının neden kesinlikle ilk 24 saat içinde ameliyat edilmesini şart koşmaktadır?\n2. Geriatrik kırılgan hastada Genel Anestezi ile Spinal Anesteziyi kanıta dayalı olarak nasıl kıyaslarsınız?\n3. Motor blok yapmadan perioperatif analjezi sağlayan ultrason kılavuzluğundaki bölgesel blok yöntemi hangisidir ve anestezi yönetiminde hangi temel ilkelere uyulmalıdır?",
    "answer_de": "1. WARUM OP-VERSORGUNG INNERHALB VON 24 STUNDEN (LEITLINIE):\n• Mortalitätsverdopplung: Eine OP-Verzögerung über 24 Stunden hinaus verdoppelt die 30-Tage-Mortalität geriatrischer Frakturpatienten signifikant!\n• Komplikationskaskade: Immobilitätsbedingte Komplikationen (Pneumonie, Dekubitus, tiefe Beinvenenthrombose, Lungenembolie, postoperatives Delir) steigen exponentiell an.\n• Ziel: Schnellstmögliche schmerzfreie Mobilisation am 1. postoperativen Tag.\n\n2. EVIDENZBASIERTER VERGLEICH ALLGEMEIN- VS. SPINALANÄSTHESIE:\n• Große RCTs (REGAIN-Trial, Cochrane-Reviews): Zeigen KEINEN signifikanten Unterschied in Bezug auf Mortalität oder Delirinzidenz zwischen Allgemein- und Spinalanästhesie!\n• Spinalanästhesie:\n - Vorteile: Vermeidung von Intubation und neuromuskulärer Blockade, weniger PONV, exzellente postoperative Frumanalgesie.\n - Nachteile & Risiken: Rasche Sympathikolyse mit schwerer arterieller Hypotonie; Kontraindikation bei therapeutischer Antikoagulation beachten (DGAI-Zeitabstände!).\n• Allgemeinanästhesie:\n - Vorteile: Bessere Steuerbarkeit des Blutdrucks (kontinuierlicher Vasopressor-Perfusor), gesicherter Atemweg bei Vollmagen/Aspirationsgefahr.\n - Nachteile: Höherer Bedarf an Hypnotika/Opioiden, Gefahr von Narkoseüberhang.\n• FAZIT: Beide Verfahren sind gleichwertig; entscheidend ist die VERMEIDUNG VON HYPOTONIE (MAP < 65 mmHg) und Narkosetiefe-Steuerung (EEG/BIS)!\n\n3. REGIONALANÄSTHESIE & SPEZIELLE GERIATRISCHE PRINZIPIEN:\n• PENG-Block (Pericapsular Nerve Group Block):\n - Ultraschallgezielte Infiltration zwischen Psoassehne und R. pubicus superior mit Lokalanästhetikum (z.B. 20 ml Ropivacain 0,2%).\n - Blockiert gezielt die nozizeptiven Gelenkäste von N. femoralis, N. obturatorius und N. accessorius obturatorius OHNE motorische Schwäche des M. quadriceps femoris -> optimale Frühmobilisation!\n - Alternative: Fascia-Iliaca-Kompartment-Block (FICB).\n• Prinzipien der Narkoseführung:\n - Keine Benzodiazepine zur Prämedikation (Delirprophylaxe!).\n - Zieldruck: Strikt MAP >= 65–70 mmHg zur Sicherung der zerebralen und renalen Perfusion (frühzeitiger Noradrenalin-Perfusor).\n - BIS-/EEG-Monitoring: Vermeidung von Burst-Suppression (starker Delirtrigger!).\n - Konsequentes aktives Wärmemanagement (Wärmedecke, Infusionswärmer; Zielkerntemperatur > 36,0 °C).",
    "answer_tr": "1. NEDEN İLK 24 SAATTE AMELİYAT (KILAVUZ):\n• Mortalite Artışı: Kalça kırığı ameliyatının 24 saatten fazla gecikmesi 30 günlük ölüm oranını iki katına çıkarır!\n• Yatak Bağımlılığı Komplikasyonları: Pnömoni, derin ven trombozu, bası yarası ve deliryum riski saatler içinde katlanır. Amaç hastayı ilk postop günde ayağa kaldırmaktır.\n\n2. GENEL ANESTEZİ Mİ SPİNAL ANESTEZİ Mİ:\n• Büyük Çalışmalar (REGAIN, Cochrane): Mortalite ve deliryum açısından iki yöntem arasında belirgin fark olmadığını göstermiştir.\n• Spinal Anestezi: Entübasyon ve kas gevşetici gerektirmez, ancak sempatik blokaj nedeniyle ani tansiyon düşüşü yaratabilir (antikoagülan kullanımına dikkat!).\n• Genel Anestezi: Tansiyon kontrolü (Noradrenalin perfüzörü ile) daha kolaydır ancak ilaç kalıntısı riski vardır.\n• Özet: Hangi yöntem seçilirse seçilsin, en kritik hedef HİPOTANSİYONDAN KAÇINMAKTIR (MAP < 65 mmHg kesinlikle engellenmelidir).\n\n3. BÖLGESEL BLOK VE GERİATRİK ANESTEZİ İLKELERİ:\n• PENG Bloğu (Pericapsular Nerve Group Block):\n - Kalça eklemini inerve eden duyusal sinir dallarını bloke eder, kuadriseps kas gücünü korur (hasta hemen basıp yürüyebilir!).\n - Alternatif: Fasya İlyaka Bloğu (FICB).\n• Anestezi Yönetimi İlkeleri:\n - Asla benzodiazepin ile premedikasyon yapmayın (deliryum nedeni!).\n - MAP >= 65-70 mmHg tutun (masada Noradrenalin hazır olsun).\n - EEG/BIS monitörizasyonu ile aşırı derin anesteziden (burst suppression) kaçının.\n - Aktif ısıtma uygulayın (vücut sıcaklığı > 36 °C).",
    "examiner_tip": "Düsseldorfer Geriatrie-Falle: 'Welches Narkoseverfahren hat bei Schenkelhalsfraktur die niedrigere Mortalität: Spinal oder Vollnarkose?' Antwort: Beide sind laut REGAIN-Trial gleichwertig! Entscheidend ist das Vermeiden von intraoperativer Hypotonie (MAP < 65 mmHg) und ein PENG-Block zur Opioideinsparung!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Sınav tuzağı: 'Kalça kırığında genel anestezi mi spinal mi daha az öldürür?' Cevap: Büyük REGAIN çalışmasına göre ikisi de eşdeğerdir! Asıl fark yaratan faktör tansiyonun düşürülmemesi (MAP < 65 mmHg olmaması) ve PENG bloğu ile ağrının kesilmesidir."
  },
  {
    "id": "q_amboss_05",
    "category": "Herz-Kreislauf, Schrittmacher & ICD",
    "amboss_pillar": "anaesthesie",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Ein 72-jähriger Patient mit ischämischer Kardiomyopathie und implantiertem 1-Kammer-ICD (Kardioverter-Defibrillator) bei Z.n. Kammerflimmern und Schrittmacherabhängigkeit soll sich einer laparoskopischen Rektumresektion unterziehen. Der Operateur beabsichtigt den intensiven Einsatz von monopolarem Elektrokauter (Diathermie).\n1. Welche lebensgefährliche Fehlfunktion kann die monopolare Diathermie bei ungeschütztem ICD auslösen (Elektromagnetische Interferenz / EMI)?\n2. Was bewirkt das Auflegen eines Magneten auf einen reinen Herzschrittmacher (PM) im Vergleich zu einem ICD?\n3. Welches prä-, intra- und postoperative Sicherheitsmanagement fordern die DGAI/DGK-Leitlinien?",
    "question_tr": "Geçirilmiş ventriküler fibrilasyon nedeniyle takılmış tek odacıklı ICD (Kardiyoverter-Defibrilatör) taşıyan ve aynı zamanda pace-bağımlı olan 72 yaşında bir hasta laparoskopik rektum rezeksiyonuna alınacaktır. Cerrah ameliyatta yoğun monopolar elektrokoter (diyatermi) kullanacağını belirtmektedir.\n1. Korumasız bir ICD'de monopolar koter hangi hayati tehlike yaratan arızalara yol açabilir (Elektromanyetik İnterferans / EMI)?\n2. Bir mıknatısın saf kalp pili (PM) üzerine konulması ile bir ICD üzerine konulması arasındaki fark nedir?\n3. DGAI ve DGK kılavuzlarının şart koştuğu ameliyat öncesi, sırası ve sonrası güvenlik protokolü nedir?",
    "answer_de": "1. GEFAHREN DER ELEKTROMAGNETISCHEN INTERFERENZ (EMI):\n• Inadäquate Schockabgabe durch Oversensing: Die hochfrequente monopolare Diathermie wird von den intrakardialen Sensorelektroden fälschlich als Kammerflimmern (VF) oder ventrikuläre Tachykardie (VT) interpretiert -> Unkontrollierte Schockabgabe (30–40 Joule) am narkotisierten Patienten! Dies kann fatale Herzrhythmusstörungen triggern und Myokardschäden erzeugen.\n• Asystolie bei Schrittmacherabhängigkeit: Die Interferenzsignale werden als Eigenaktionen des Herzens fehlgedeutet -> Inhibierung der Schrittmacherstimulation -> Akute Asystolie!\n• Aggregatbeschädigung / Reprogrammierung in den Back-up-Sicherheitsmodus.\n\n2. MAGNETAUFLAGE IM VERGLEICH (KARDINALE PRÜFUNGSFRAGE!):\n• BEIM REINEN HERZSCHRITTMACHER (PM):\n - Die Magnetauflage schaltet den Schrittmacher in einen festfrequenten ASYNCHRONEN MODUS (VOO oder DOO, meist mit 85–100 bpm).\n - Verhindert die Schrittmacher-Inhibierung durch Kauter-Signale!\n• BEIM ICD (DEFIBRILLATOR):\n - Die Magnetauflage DEAKTIVIERT DIE TACHYARRHYTHMIE-ERKENNUNG / SCHOCKABGABE!\n - WICHTIG: Die Magnetauflage schaltet die Schrittmacherfunktion beim ICD in der Regel NICHT in den asynchronen Modus VOO! Ein schrittmacherabhängiger ICD-Patient ist durch bloße Magnetauflage NICHT vor Asystolie geschützt, sondern muss vorab durch den Kardiologen per Programmiergerät auf asynchronen Modus (VOO) umprogrammiert werden!\n\n3. DGAI/DGK-SICHERHEITSMANAGEMENT:\n• Präoperativ: CIED-Ausweis prüfen (Hersteller, Modell, Batteriestatus, Stimulationsabhängigkeit). Bei ICD: Tachyarrhythmie-Therapie deaktivieren (per Programmiergerät oder Magnetauflage).\n• Intraoperativ:\n - EXTERNER DEFIBRILLATOR MIT GEKLEBTEN PADS VOR EINLEITUNG: Klebe-Defibrillatorelektroden zwingend vor Narkoseeinleitung in Anterior-Posterior-Position am Patienten anbringen und Defibrillator am Platz betriebsbereit halten!\n - Diathermie-Regeln: Bipolaren Kauter bevorzugen. Neutralelektrode so anbringen, dass der Strompfad nicht das ICD-Aggregat oder die Sonden kreuzt (z.B. am Oberschenkel). Nur kurze Kauterstöße (< 5 Sekunden).\n - Monitoring: Kontinuierliches EKG und Pulsoxymetrie (Plethysmogramm zeigt Perfusion bei EKG-Kauterartefakten).\n• Postoperativ: Lückenlose EKG-Überwachung im Aufwachraum bis zur Reaktivierung des ICDs; Re-Programmierung und Funktionskontrolle vor Verlegung auf Normalstation!",
    "answer_tr": "1. ELEKTROMANYETİK İNTERFERANS (EMI) TEHLİKELERİ:\n• Yanlış Şok Verilmesi (Oversensing): Monopolar koter akımları cihaz tarafından ventriküler fibrilasyon sanılır -> Ameliyat masasındaki hastaya aniden 40 Joule ölümcül şok boşalır!\n• Pace İnhibisyonu ve Asistoli: Pace bağımlı hastada cihaz koter parazitini kalbin kendi ritmi sanır ve uyarı vermeyi durdurur -> Ani asistoli gelişir!\n• Cihazın hasar görmesi veya sıfırlanması.\n\n2. MIKNATIS ETKİSİ (EN ÇOK SORULAN SINAV SORUSU!):\n• SAF KALP PİLİNDE (Pacemaker):\n - Mıknatıs konulduğunda cihaz sabit hızlı ASENKRON MODA (VOO/DOO, 85-100/dk) geçer. Koterden etkilenip durmaz.\n• ICD'DE (Defibrilatör):\n - Mıknatıs konulduğunda ŞOK ÖZELLİĞİ İPTAL OLUR (koter nedeniyle boş yere şok atmaz).\n - DİKKAT: Mıknatıs ICD'nin pace fonksiyonunu asenkron VOO moduna GEÇİRMEZ! Bu nedenle pace-bağımlı ICD hastası ameliyattan önce kardiyolog tarafından programlayıcı cihazla asenkron moda ayarlanmalıdır!\n\n3. DGAI/DGK GÜVENLİK PROTOKOLÜ:\n• Ameliyat Öncesi: Pil kartı kontrolü, ICD şok özelliğinin kapatılması (mıknatıs veya cihazla).\n• Ameliyat Sırasında:\n - MASADA HARİCİ DEFİBRİLATÖR PEDLERİ: Anestezi indüksiyonundan ÖNCE anterior-posterior harici defibrilatör pedleri yapıştırılmış olmalıdır!\n - Koter Kuralları: Mümkünse bipolar koter. Nötr plak kotere yakın, pilden uzak yere (ör. uyluk) yapıştırılır. Koter 4-5 saniyeden uzun basılmaz.\n - Monitörizasyon: EKG parazitliyken nabzı puls oksimetre dalgasından takip edin.\n• Ameliyat Sonrası: Cihaz açılana kadar derlenmede sürekli monitörizasyon; kardiolog kontrolüyle cihazın tekrar aktive edilmesi.",
    "examiner_tip": "Prof. Annecke / Kienbaum Klassiker: 'Was passiert, wenn Sie einen Magneten auf einen ICD legen?' Kardinalfehler: Zu sagen, er schalte in den asynchronen Schrittmachermodus VOO! Richtig: Er schaltet nur die Schocktherapie ab! Bei schrittmacherabhängigen Patienten muss extern auf VOO umprogrammiert werden und Defi-Pads MÜSSEN vor Einleitung kleben!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jüri klasiği: 'ICD üzerine mıknatıs koyarsan ne olur?' K.O. Hatası: 'Pili sabit hıza (VOO) geçirir' demek! Doğrusu: Sadece şok özelliğini kapatır, pili asenkron yapmaz! Pace bağımlı hastada önceden VOO'ya ayarlanmalı ve indüksiyondan önce harici defibrilatör pedleri yapıştırılmalıdır!"
  },
  {
    "id": "q_amboss_06",
    "category": "Bariatrie & Adipositas permagna",
    "amboss_pillar": "anaesthesie",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Eine 44-jährige Patientin (Körpergröße 165 cm, Ist-Gewicht 145 kg -> BMI 53,3 kg/m², Idealgewicht / IBW ca. 58 kg) stellt sich zur laparoskopischen Sleeve-Gastrektomie vor. Sie leidet unter schwerem obstruktivem Schlafapnoe-Syndrom (OSAS, AHI 48/h) und arterieller Hypertonie.\n1. Wie gestalten Sie die Präoxygenierung und Patientenlagerung zur Maximierung der Apnoetoleranz ('Ramped Position')?\n2. Wie dosieren Sie Propofol, Rocuronium und Sugammadex pharmakologisch korrekt (Ist- vs. Ideal- vs. Magergewicht)?\n3. Welche lungenprotektive Beatmungsstrategie verhindert intraoperative Atelektasen und wie berechnen Sie das Tidalvolumen?",
    "question_tr": "Laparoskopik tüp mide (sleeve gastrektomi) planlanan 44 yaşında bir kadın hasta (Boy 165 cm, Gerçek Kilo 145 kg -> VKİ 53,3 kg/m², İdeal Kilo / IBW yaklaşık 58 kg). Ağır obstrüktif uyku apnesi (OSAS, AHI 48/saat) ve hipertansiyonu mevcuttur.\n1. Apne toleransını en üst düzeye çıkarmak için preoksijenizasyonu ve hasta pozisyonunu ('Ramped Position') nasıl ayarlarsınız?\n2. Propofol, Roküronyum ve Sugammadeks dozlarını farmakolojik olarak nasıl hesaplarsınız (Gerçek Kilo vs İdeal Kilo vs Yağsız Vücut Ağırlığı)?\n3. İntraoperatif atelektazileri önleyen akciğer koruyucu ventilasyon stratejiniz nedir ve tidal volümü nasıl hesaplarsınız?",
    "answer_de": "1. LAGERUNG & PRÄOXYGENIERUNG:\n• Ramped Position (Kopf-Oberkörper-Hochlagerung / 'Ear-to-Sternal-Notch'):\n - Anhebung von Kopf, Nacken und Schultern durch Keilkissen oder Tischverstellung, sodass der äußere Gehörgang und das Jugulum (Sternum-Oberkante) auf einer horizontalen Linie liegen.\n - Verdrängt intraabdominelles Fettgewebe nach kaudal, entlastet das Zwerchfell, vergrößert die funktionelle Residualkapazität (FRC) und erleichtert die Laryngoskopie dramatisch.\n• Präoxygenierung:\n - Mindestens 3–5 Minuten mit 100% O2 unter dicht sitzender Maske mit CPAP/PEEP (5–10 cmH2O) oder High-Flow-Nasenkanüle (HFNC/THRIVE).\n - Verdoppelt die apnoische Desaturationszeit (verhindert den steilen SpO2-Absturz nach Muskelrelaxierung).\n\n2. PHARMAKOLOGISCHE DOSIERUNG (K.O.-KRITERIUM):\n• PROPOFOL:\n - Induktion: Nach LEAN BODY WEIGHT (LBW / Magergewicht) ca. 2 mg/kg LBW (~110–130 mg), NICHT nach Ist-Gewicht (145 kg x 2 mg = 290 mg -> massiver Kreislaufkollaps!).\n - Erhaltung: Nach TOTAL BODY WEIGHT (TBW) infolge des großen Verteilungsvolumens und Clearance.\n• ROCURONIUM: STRIKT NACH IDEALGEWICHT (IBW)!\n - Dosis: 0,6 mg/kg IBW (bei 58 kg = ~35 mg; bei RSI 1,0 mg/kg IBW = ~60 mg).\n - Dosierung nach Ist-Gewicht (145 kg = 145 mg) führt zu massiver Überdosierung und stundenlanger neuromuskulärer Blockade!\n• SUGAMMADEX: NACH REALEM KÖRPERGEWICHT (TBW)!\n - Dosis: 2 mg/kg TBW bei Wiederauftreten von T2 (~290 mg), 4 mg/kg TBW bei tiefem Block (PTC 1–2, ~580 mg), 16 mg/kg TBW bei Notfall-Rescue.\n - Rationale: Sugammadex verkapselt freies Rocuronium im gesamten intravasalen und extrazellulären Raum 1:1 und muss nach dem Gesamtvolumen dosiert werden.\n• SUFENTANIL / FENTANYL: Nach IBW oder LBW (Atemdepression bei OSAS!).\n\n3. LUNGENPROTEKTIVE BEATMUNG:\n• Tidalvolumen (Vt): 6–8 ml/kg NACH IDEALGEWICHT (IBW = 58 kg -> Vt ca. 350–450 ml)! Niemals nach Ist-Gewicht ventilieren (145 kg x 7 ml = 1.000 ml -> fatales Volu- und Barotrauma!).\n• PEEP-Titration: Höherer PEEP (10–14 cmH2O zwingend erforderlich, um Alveolarkollaps gegen das Gewicht der Thoraxwand und das Kapnoperitoneum zu verhindern).\n• Rekrutierungsmanöver (Alveolar Recruitment): Nach Intubation und Umlagerung (z.B. 30 cmH2O für 10 s unter Kreislaufkontrolle).\n• Extubation: Vollständig wach in 30–45° Oberkörperhochlagerung nach nachgewiesener Relaxometrie (TOF-Ratio >= 0,9)!",
    "answer_tr": "1. POZİSYON VE PREOKSİJENİZASYON:\n• Ramped Pozisyonu (Baş-Boyun Yükseltme / 'Ear-to-Sternal-Notch'):\n - Dış kulak yolu ile sternum üst çentiği aynı yatay düzleme gelecek şekilde omuz ve baş desteklenir.\n - Karın yağlarının diyaframa basısını azaltır, Fonksiyonel Rezidüel Kapasiteyi (FRC) artırır ve laringoskopiyi çok kolaylaştırır.\n• Preoksijenizasyon: %100 O2 ile en az 3-5 dk CPAP/PEEP (5-10 cmH2O) eşliğinde maskeyle yapılır. Kas gevşetici sonrası ani SpO2 çakılmasını önler.\n\n2. FARMAKOLOJİK DOZ HESAPLAMA (K.O. KRİTERİ):\n• PROPOFOL: İndüksiyonda YAĞSIZ VÜCUT AĞIRLIĞINA (LBW) göre (~110-130 mg verilir). Gerçek kiloya göre verilirse (145 kg x 2 = 290 mg) tansiyon çöker ve kardiyak arrest olur!\n• ROKÜRONYUM: KESİNLİKLE İDEAL KİLOYA (IBW) GÖRE!\n - Doz: 0,6-1,0 mg/kg IBW (58 kg için 35-60 mg). Gerçek kiloya göre (145 mg) verilirse hasta saatlerce uyanamaz ve felç kalır!\n• SUGAMMADEKS: GERÇEK VÜCUT AĞIRLIĞINA (TBW) GÖRE!\n - Doz: 2-4 mg/kg TBW (145 kg x 2-4 mg = 290-580 mg). Sugammadeks kandaki tüm roküronyum moleküllerini 1:1 bağladığı için gerçek dağılım hacmine göre verilmelidir.\n• Opiyatlar: İdeal kiloya göre verilir (uyku apnesinde solunum durmasını önlemek için).\n\n3. AKCİĞER KORUYUCU VENTİLASYON:\n• Tidal Hacim: İDEAL KİLOYA (IBW) GÖRE 6-8 ml/kg (Vt = 350-450 ml)! Gerçek kiloya göre 1000 ml ventilasyon yapmak akciğeri patlatır (barotravma/volutravma)!\n• Yüksek PEEP (10-14 cmH2O): Göğüs duvarı ağırlığı ve karın gazına karşı atelektaziyi önler.\n• Ekstübasyon: Hasta tam uyanık, başı 45° dik ve TOF oranı >= %90 iken ekstübe edilir.",
    "examiner_tip": "Düsseldorfer Bariatrie-Klassiker: 'Eine 150-kg-Patientin: Wie viel Rocuronium und wie viel Sugammadex geben Sie?' K.O.-Kriterium: Rocuronium nach IDEALGEWICHT (sonst massive Überdosierung!), Sugammadex nach REALEM KÖRPERGEWICHT (sonst unvollständige Antagonisierung)! Tidalvolumen strikt nach Idealgewicht (6-8 ml/kg IBW)!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jürinin en sevdiği soru: '150 kg hastaya Roküronyum ve Sugammadeks'i hangi kiloya göre verirsin?' K.O. Kuralı: Roküronyum İDEAL KİLOYA (yoksa aşırı doz!), Sugammadeks GERÇEK KİLOYA göre verilir! Tidal hacim mutlaka ideal kiloya (IBW) göre ayarlanır!"
  },
  {
    "id": "q_amboss_07",
    "category": "Intensivmedizin & Weaning",
    "amboss_pillar": "intensiv",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Ein 69-jähriger Patient mit schwerer COPD (GOLD IV) wurde vor 11 Tagen wegen septischem Schock und Pneumonie intubiert. Die Infektion ist saniert, Katecholamine wurden beendet, der Patient ist wach und kooperativ. Unter druckunterstützter Spontanatmung (PSV 12 mbar, PEEP 6 mbar, FiO2 0,35) beträgt die SpO2 95%.\n1. Welche formalen Kriterien müssen erfüllt sein, um einen Spontaneous Breathing Trial (SBT) zu starten?\n2. Wie führen Sie den SBT durch, wie berechnen Sie den RSBI (Rapid Shallow Breathing Index nach Yang & Tobin) und wie lauten die Abbruchkriterien?\n3. Ab welchem Zeitpunkt besteht die Indikation zur perkutanen Dilatationstracheotomie (PDT) und welche Kontraindikationen müssen Sie beachten?",
    "question_tr": "Ağır KOAH'ı (GOLD IV) olan 69 yaşında bir hasta 11 gün önce septik şok ve pnömoni nedeniyle entübe edilmiştir. Enfeksiyon gerilemiş, katekolaminler kesilmiş, hasta uyanık ve kooperedir. Basınç destekli spontan solunumda (PSV 12 mbar, PEEP 6 mbar, FiO2 0,35) SpO2 %95'tir.\n1. Spontan Solunum Denemesini (SBT) başlatmak için hangi formel kriterler sağlanmalıdır?\n2. SBT'yi nasıl uygularsınız, Yang & Tobin Hızlı Yüzeysel Solunum İndeksini (RSBI) nasıl hesaplarsınız ve denemeyi sonlandırma kriterleri nelerdir?\n3. Perkütan dilatasyonel trakeostomi (PDT) endikasyonu ne zaman doğar ve hangi kontrendikasyonlara dikkat edilmelidir?",
    "answer_de": "1. KRITERIEN FÜR WEANING-BEREITSCHAFT (SBT-START):\n• Kausalität behoben: Besserung der primären respiratorischen/septischen Ursache.\n• Adäquate Oxygenierung: PaO2/FiO2 > 150–200 mmHg bei PEEP <= 8 cmH2O und FiO2 <= 0,40 (PaO2 >= 60 mmHg).\n• Hämodynamische Stabilität: Kein oder nur minimale Vasopressorendosis (Noradrenalin < 0,05 µg/kg/min), keine myokardiale Ischämie, Herzfrequenz < 120 bpm.\n• Neurologisch & Atemmechanik: Wach, kontaktfähig, adäquater Hustenstoß, intakter Schluckreflex, keine Erschöpfung.\n• Säure-Basen-Haushalt: Kompensiert (pH > 7,30).\n\n2. SBT-DURCHFÜHRUNG, RSBI & ABBRUCHKRITERIEN:\n• Durchführung: 30 Minuten Spontanatmung am Beatmungsgerät mit PSV 0–5 cmH2O und PEEP 0–5 cmH2O (oder am T-Stück mit O2-Vorlage).\n• RSBI (Rapid Shallow Breathing Index nach Yang & Tobin):\n - Formel: RSBI = Atemfrequenz (f in 1/min) geteilt durch das Tidalvolumen (Vt in Litern).\n - Interpretation: Ein RSBI < 105 sagt einen erfolgreichen Extubationserfolg voraus! Ein RSBI > 105 belegt eine ineffektive, flache Tachypnoe mit drohender respiratorischer Erschöpfung.\n• SBT-Abbruchkriterien:\n - Atemfrequenz > 35/min oder Zunahme um > 50%.\n - SpO2 < 90% (oder paO2 < 60 mmHg bei FiO2 0,4).\n - Tachykardie (HF > 140/min oder Zunahme um > 20%) oder neue Tachyarrhythmie.\n - Blutdruckanstieg (systolisch > 180 mmHg) oder -abfall (< 90 mmHg).\n - Klinische Erschöpfung: Schwitzen, Agitation, thorakoabdominelle Paradoxie (Schaukelatmung).\n\n3. PERKUTANE DILATATIONSTRACHEOTOMIE (PDT):\n• Indikation & Zeitpunkt: Bei absehbar prolongiertem Weaning (> 10–14 Tage Intubation) oder gescheiterten Extubationsversuchen empfiehlt die Leitlinie die elektive perkutane Dilatationstracheotomie (PDT nach Ciaglia / Single-Step-Dilatator).\n• Vorteile: Reduktion des Atemwegswiderstands und Totraums, Schonung der Stimmbänder, leichtere Bronchialtoilette, orale Ernährung, Reduktion von Sedativa.\n• Kontraindikationen der PDT (dann chirurgische Tracheotomie):\n - Schwere Gerinnungsstörung (Thrombozyten < 50.000/µl, Quick < 50%).\n - Lokale Infektion am Hals / Phlegmone / Verbrennung.\n - Anatomische Hindernisse: Struma permagna, ausgeprägte Trachealdeformität, instabile HWS-Fraktur.\n - Schwere Hypoxie (FiO2 > 0,7 oder PEEP > 10–12 cmH2O während des Eingriffs nicht tolerabel).",
    "answer_tr": "1. WEANING VE SBT BAŞLATMA KRİTERLERİ:\n• Nedenin Çözülmesi: Primer solunum yetmezliği ve sepsisin kontrol altına alınmış olması.\n• Yeterli Oksijenasyon: PaO2/FiO2 > 150-200 mmHg (PEEP <= 8 cmH2O ve FiO2 <= 0,40 iken).\n• Hemodinamik Stabilite: Katekolamin ihtiyacının olmaması veya minimal olması, sinüs ritmi (KAH < 120/dk).\n• Nörolojik Durum: Uyanık, kooperatif, yeterli öksürük refleksi, sekresyonu yutabilme.\n• Asit-Baz: Kompanse pH (> 7,30).\n\n2. SBT UYGULAMASI, RSBI VE SONLANDIRMA KRİTERLERİ:\n• Uygulama: Cihazda PSV 0-5 cmH2O ve PEEP 0-5 cmH2O ile 30 dakika spontan solutulur.\n• RSBI (Yang & Tobin Hızlı Yüzeysel Solunum İndeksi):\n - Formül: RSBI = Solunum Sayısı (dk'da) / Tidal Hacim (Litre cinsinden).\n - Değerlendirme: RSBI < 105 ise ekstübasyon başarısı yüksektir! RSBI > 105 ise yüzeysel hızlı solunum ve yorulmayı gösterir (ekstübe edilmez!).\n• SBT Başarısızlık Kriterleri: Solunum sayısı > 35/dk, SpO2 < %90, Nabız > 140/dk, Tansiyon > 180 veya < 90 mmHg, terleme, ajitasyon, paradoksal solunum.\n\n3. PERKÜTAN DİLATASYONEL TRAKEOSTOMİ (PDT):\n• Zamanlama: Uzamış mekanik ventilasyonda (> 10-14 gün) kılavuzlar perkütan trakeostomiyi (Ciaglia tekniği) önerir.\n• Avantajları: Ölü boşluğu ve solunum direncini azaltır, ses tellerini korur, aspirasyonu kolaylaştırır, sedasyonu kesmeyi sağlar.\n• PDT Kontrendikasyonları (Cerrahi trakeostomi gerekir): Trombosit < 50.000/µL, Quick < %50, boyunda enfeksiyon, dev guatr, instabil boyun kırığı, ağır oksijenasyon bozukluğu (PEEP > 10).",
    "examiner_tip": "Düsseldorfer Intensiv-Klassiker: 'Wie berechnen Sie den Yang-Tobin-Index (RSBI) und was bedeutet ein Wert von 120?' Antwort: RSBI = Atemfrequenz / Tidalvolumen in Litern. Ein Wert > 105 belegt eine flache Tachypnoe und sagt Weaning-Versagen voraus! Der Patient darf nicht extubiert werden!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Yoğun bakım sorusu: 'Yang-Tobin (RSBI) indeksini nasıl hesaplarsın, 120 çıkarsa ne yaparsın?' Cevap: RSBI = Solunum Sayısı / Tidal Volüm (Litre). Değerin > 105 olması yorulmayı ve yetmezliği gösterir, hasta kesinlikle ekstübe edilmez!"
  },
  {
    "id": "q_amboss_08",
    "category": "Spezielle Schmerztherapie & CRPS",
    "amboss_pillar": "schmerz",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Eine 52-jährige Patientin stellt sich 7 Wochen nach einer konservativ im Gips behandelten distalen Radiusfraktur in der Schmerzambulanz vor. Sie klagt über quälende, brennende Ruheschmerzen in der Hand, die in keinem Verhältnis zum ursprünglichen Trauma stehen. Die Hand ist livide verfärbt, ödematös geschwollen, überwärmt und schweißnass. Bereits das sanfte Bestreichen der Haut mit einem Wattebausch löst stärkste Schmerzen aus (NRS 9/10).\n1. Welche Diagnose stellen Sie, welcher Subtyp liegt vor und anhand welcher Kriterien (Budapest-Kriterien) sichern Sie den Befund?\n2. Wie definieren Sie Allodynie und Hyperalgesie pathophysiologisch?\n3. Wie lautet das multimodale Stufenkonzept (Physiotherapie, medikamentös, interventionell) und welches Vorgehen ist ein gravierender Behandlungsfehler?",
    "question_tr": "Alçıda konservatif tedavi edilen el bileği (distal radius) kırığından 7 hafta sonra 52 yaşında bir kadın hasta ağrı polikliniğine başvurur. Elinde ilk travmayla orantısız, dayanılmaz yanıcı istirahat ağrısından yakınmaktadır. El morarmış (livide), ödemli, sıcak ve ter içindedir. Cilde pamukla hafifçe dokunulması bile şiddetli ağrı krizine (NRS 9/10) yol açmaktadır.\n1. Hangi tanıyı koyarsınız, hangi alt tip söz konusudur ve tanıyı hangi kriterlerle (Budapeşte Kriterleri) doğrularsınız?\n2. Allodini ve Hiperaljeziyi patofizyolojik olarak nasıl tanımlarsınız?\n3. Çok modlu basamaklı tedavi konsepti (fizyoterapi, ilaç, girişimsel) nasıldır ve hangi uygulama vahim bir hekimlik hatasıdır?",
    "answer_de": "1. DIAGNOSE & BUDAPEST-KRITERIEN:\n• Diagnose: COMPLEX REGIONAL PAIN SYNDROME (CRPS) TYP I (Morbus Sudeck / Reflexdystrophie, da keine primäre Nervenläsion vorliegt; Typ II wäre Kausalgie mit nachgewiesener Nervenläsion).\n• Validierte Budapest-Kriterien (AWMF-Leitlinie):\n 1. Anhaltender Schmerz, der durch das Anfangstrauma nicht mehr erklärt wird.\n 2. Mindestens 1 Symptom in 3 von 4 Kategorien (Anamnese) UND mindestens 1 Befund in 2 von 4 Kategorien (Untersuchung):\n    - Sensorisch: Hyperalgesie oder Allodynie.\n    - Vasomotorisch: Temperaturasymmetrie (> 1°C) oder Hautfarbdifferenz (livide/erythematös).\n    - Sudomotorisch / Ödem: Ödem oder Hyperhidrosis (Schweißasymmetrie).\n    - Motorisch / Trophisch: Verminderte Beweglichkeit, Dystonie, Tremor oder verändertes Nagel-/Haarwachstum.\n\n2. PATHOPHYSIOLOGISCHE BEGRIFFE:\n• ALLODYNIE: Schmerzempfindung durch einen Reiz, der physiologischerweise keinen Schmerz auslöst (z.B. sanftes Bestreichen mit Wattebausch oder Kleidung).\n• HYPERALGESIE: Übersteigerte, unverhältnismäßig starke Schmerzreaktion auf einen Reiz, der normalerweise nur leichten Schmerz erzeugt (z.B. Nadelstich).\n\n3. MULTIMODALES THERAPIEKONZEPT & KARDINALFEHLER:\n• GRUNDPFEILER PHYSIO- & ERGOTHERAPIE:\n - Aktive und passive Mobilisation STRIKT IM SCHMERZFREIEN BEREICH!\n - Spiegeltherapie (Mirror Therapy) und Graded Motor Imagery zur ZNS-Reorganisation.\n• KARDINALFEHLER (K.O.-KRITERIUM):\n - Erneute Ruhigstellung im Gips oder einer Schiene ist strengstens kontraindiziert! Ruhigstellung aggraviert das CRPS und führt zu irreversibler Gelenkeinsteifung und Dystrophie!\n• Medikamentöse Stufentherapie:\n - Neuropathische Schmerztherapie: GABAPENTINOIDE (Pregabalin 150–600 mg/Tag oder Gabapentin) zur Dämpfung der spinalen Erregbarkeit; alternativ Duloxetin / Amitriptylin.\n - Entzündungshemmung im akuten Stadium (< 3–6 Monate): Kortisonstoß (Prednisolon 100 mg/Tag oral für 3 Tage, dann wöchentlich um 25 mg ausschleichen).\n - Bisphosphonate (z.B. Alendronat / Zoledronat) bei nachgewiesenem Knochenumbau.\n - Radikalfänger: Vitamin C (500 mg/Tag).\n• Interventionelle Verfahren:\n - Sympathikusblockade: STELLATUM-BLOCKADE (Ganglion stellatum) bei oberer Extremität mit Lokalanästhetika (z.B. Ropivacain 0,2%). Bricht den sympathisch unterhaltenen Schmerz.\n - Bei Chronifizierung: Spinal Cord Stimulation (SCS / Rückenmarkstimulation).",
    "answer_tr": "1. TANI VE BUDAPEŞTE KRİTERLERİ:\n• Tanı: KOMPLEKS BÖLGESEL AĞRI SENDROMU (CRPS) TİP 1 (Sudeck Atrofisi; belirgin bir sinir hasarı olmadığı için Tip 1'dir. Sinir kesisi/hasarı olsaydı Tip 2 / Kozalji olurdu).\n• Budapeşte Kriterleri (AWMF Kılavuzu):\n 1. İlk travmayla açıklanamayan sürekli ağrı.\n 2. 4 kategorinin en az 3'ünde semptom ve en az 2'sinde muayene bulgusu:\n    - Duyusal: Hiperaljezi veya Allodini.\n    - Vazomotor: Sıcaklık farkı (> 1°C) veya renk değişikliği (morarma/kızarma).\n    - Sudomotor/Ödem: Ödem veya aşırı terleme.\n    - Motor/Trofik: Hareket kısıtlılığı, titreme, tırnak/kıl uzamasında bozulma.\n\n2. AĞRI KAVRAMLARI:\n• ALLODİNİ: Normalde ağrı oluşturmayan bir uyaranla (ör. pamuk dokundurulması, rüzgar esmesi) şiddetli ağrı hissedilmesi.\n• HİPERALJEZİ: Normalde hafif ağrı yapacak bir uyarana (ör. iğne batması) aşırı abartılı ağrı yanıtı verilmesi.\n\n3. ÇOK MODLU TEDAVİ VE VAHİM HATA:\n• TEMEL DİREK: FİZYOTERAPİ VE ERGOTERAPİ:\n - Ağrısız sınırlar içinde kalarak erken hareket! Ayna tedavisi (Mirror therapy).\n• VAHİM HATA (K.O. KRİTERİ):\n - Eli yeniden alçıya veya atele almak kesinlikle YASAKTIR! İmmobilizasyon CRPS tablosunu alevlendirir, kontraktür ve sakatlığa yol açar!\n• İlaç Tedavisi:\n - Nöropatik İlaçlar: Gabapentinoidler (Pregabalin 150-600 mg/gün veya Gabapentin), Amitriptilin veya Duloksetin.\n - Akut Dönemde Kortizon: Prednizolon 100 mg/gün ile başlanıp haftalık azaltılarak kesilir.\n - Kemik döngüsü için Bifosfonat.\n• Girişimsel Tedavi: Sempatik Gangliyon Bloğu (Stellat Gangliyon Bloğu). Kronikleşirse Omurilik Stimülasyonu (SCS).",
    "examiner_tip": "Düsseldorfer Schmerz-Klassiker: 'Patientin mit V.a. CRPS nach Radiusfraktur – legen Sie zur Schmerzlinderung wieder einen Gips an?' K.O.-Kriterium: NIEMALS! Erneute Ruhigstellung verschlimmert die Dystrophie fatal. Budapest-Kriterien nennen, Pregabalin, Physiotherapie und Stellatumblockade einleiten!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jüri tuzağı: 'Kırık sonrası eli morarıp yanan CRPS hastasına ağrısı geçsin diye tekrar alçı yapar mısınız?' K.O. Kriteri: ASLA! Alçıya almak hastalığı daha da azdırır. Budapeşte kriterlerini say, Pregabalin başla, fizyoterapi ve Stellat blokajı planla!"
  },
  {
    "id": "q_amboss_09",
    "category": "Spezielle Schmerztherapie & CRPS",
    "amboss_pillar": "schmerz",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Ein 64-jähriger Patient mit metastasiertem Bronchialkarzinom (multiple Knochenmetastasen in LWS und Becken) leidet unter progredienten Schmerzen. Bislang nimmt er Ibuprofen 3x 600 mg und Novaminsulfon 4x 1 g täglich ein. Die Schmerzstärke auf der NRS beträgt dennoch in Ruhe 5/10 und bei Belastung 8/10.\n1. Wie eskalieren Sie die Schmerztherapie nach dem WHO-Stufenschema und wie lauten die 4 Grundregeln der WHO?\n2. Welche Begleitmedikation MUSS vom ersten Tag der Opioidtherapie zwingend verordnet werden und warum tritt hier keine Toleranz ein?\n3. Wie therapieren Sie Durchbruchschmerzen (Breakthrough Pain) und wie berechnen Sie die Bedarfsdosis?",
    "question_tr": "Kemik metastazları olan 64 yaşında akciğer kanseri bir hasta şiddetli ağrılardan yakınmaktadır. İbuprofen 3x 600 mg ve Metamizol 4x 1 g almasına rağmen ağrı skoru istirahatte NRS 5/10, hareketle 8/10'dur.\n1. WHO (Dünya Sağlık Örgütü) basamak şemasına göre tedaviyi nasıl basamaklandırırsınız ve WHO'nun 4 temel kuralı nedir?\n2. Opioid tedavisinin ilk gününden itibaren hangi koruyucu ilaç ZORUNLU olarak reçete edilmelidir ve vücut bu yan etkiye neden tolerans geliştirmez?\n3. Ani alevlenen kırılma ağrılarını (Breakthrough Pain) nasıl tedavi edersiniz ve kurtarma dozunu nasıl hesaplarsınız?",
    "answer_de": "1. WHO-STUFENSCHEMA & DIE 4 GRUNDREGELN:\n• Stufenwechsel: Direkte Eskalation auf WHO-STUFE III (starkes Opioid)! Bei starken Tumorschmerzen (NRS >= 6) wird Stufe II (schwache Opioide wie Tramadol/Tilidin) übersprungen, da sie ein Wirksamkeitsplateau (Ceiling-Effekt) haben.\n• Initialtherapie Stufe III: Retardiertes MORPHIN (z.B. 2x 30 mg p.o.) oder OXYCODON (z.B. 2x 10–20 mg p.o.). Das Nicht-Opioid (Novaminsulfon) wird beibehalten (synergistischer Effekt bei Knochenschmerzen).\n• DIE 4 GRUNDREGELN DER WHO:\n 1. By the mouth: Bevorzugung oral/transdermaler Darreichungsformen (keine Spritzen).\n 2. By the clock: Feste Zeiteinnahme nach der Uhr (z.B. alle 12h bei Retardtabletten), NICHT erst bei Wiederauftreten von Schmerzen!\n 3. By the ladder: Stufenweise Dosisanpassung nach Schmerzintensität ohne starre Obergrenze.\n 4. For the individual: Individuelle Dosistitration angepasst an den Patienten.\n\n2. ZWINGENDE BEGLEITMEDIKATION (K.O.-KRITERIUM):\n• PROPHYLAXE: FIXE LAXANTIEN-VERORDNUNG AB TAG 1 (z.B. MACROGOL 1–2 Beutel/Tag p.o.)!\n• Pathophysiologie: Opioide binden an periphere Mu-Rezeptoren im Plexus myentericus des Darms -> Hemmung der Peristaltik, Pylorusspasmus, Steigerung der Wasserresorption aus dem Stuhl.\n• Warum keine Toleranz: Während gegen Übelkeit, Sedierung und Atemdepression nach wenigen Tagen eine ZNS-Toleranz entsteht, adaptieren die gastrointestinalen Mu-Rezeptoren NIEMALS! Die Obstipation bleibt lebenslang bestehen und führt ohne Prophylaxe zu Koprostase, Subileus und Kolonperforation!\n• Bei therapierefraktärer Obstipation: PAMORA (peripher wirksame Mu-Opioid-Antagonisten wie Naloxegol oder Methylnaltrexon).\n\n3. THERAPIE VON DURCHBRUCHSCHMERZEN (BREAKTHROUGH PAIN):\n• Definition: Vorübergehende, abrupte Schmerzspitze trotz suffizienter Basismedikation.\n• Dosisberechnung: Unretardiertes Opioid in Höhe von 1/6 (ca. 10–16%) der 24-Stunden-Gesamtdosis des Basismoleküls (z.B. bei 120 mg Morphin/Tag -> Bedarfsdosis 20 mg unretardiertes Morphin oral).\n• Schnell anflutende Fentanyl-Präparate: Bei Knochenmetastasen tritt der Schmerzgipfel oft binnen 3–5 Minuten auf. Hier ist orales Morphin (Wirkeintritt 30 min) zu langsam -> Einsatz von TRANSMUKOSALEM ODER NASALEM FENTANYL (Sublingualtablette, Buccaltablette oder Fentanyl-Nasenspray), das innerhalb von 5–10 Minuten wirkt!",
    "answer_tr": "1. DSÖ (WHO) BASAMAK ŞEMASI VE 4 TEMEL KURAL:\n• Basamak Geçişi: Doğrudan WHO 3. BASAMAĞA (Güçlü Opioid) geçilir! Şiddetli ağrıda (NRS >= 6) tavan etkisi olan 2. basamak zayıf opioidler (Tramadol vb.) atlanır.\n• Başlangıç: Uzun etkili (retard) MORFİN (2x 30 mg) veya OKSİKODON (2x 10-20 mg). Metamizol kemik ağrısı için kesilmez, kombine edilir.\n• WHO 4 Temel Kuralı:\n 1. Ağızdan (By mouth): Öncelik oral/transdermal yoldur.\n 2. Saate göre (By clock): Ağrı başladığında değil, saatinde (12 saatte bir) düzenli alınır.\n 3. Basamağa göre (By ladder): Ağrı şiddetine göre doz artırılır.\n 4. Kişiye özel (For the individual): Dozun tavan sınırı yoktur, hastaya göre titre edilir.\n\n2. ZORUNLU KORUYUCU İLAÇ (K.O. KRİTERİ):\n• İLK GÜNDEN İTİBAREN LAKSATİF (MAKROGOL 1-2 saşe/gün) ZORUNLUDUR!\n• Neden Tolerans Gelişmez: Morfinin bulantı, uyku hali ve solunum baskılama etkisine birkaç günde tolerans gelişir; ancak bağırsak mu-reseptörleri ASLA TOLERANS GELİŞTİRMEZ! Kabızlık ömür boyu sürer ve laksatif verilmezse ileus ve bağırsak delinmesine yol açar!\n• Dirençli vakalarda periferik opioid blokeri (Naloksegol / PAMORA) verilir.\n\n3. KIRILMA AĞRISININ (BREAKTHROUGH PAIN) TEDAVİSİ:\n• Kurtarma Dozu: 24 saatlik toplam bazal dozun 1/6'sı (%10-16'sı) kadar hızlı etkili opioid verilir (Örn: Günlük 120 mg morfine karşılık 20 mg hızlı morfil oral).\n• Transmukozal Fentanil: Kemik metastazı ağrıları 3-5 dakikada zirve yapar. Oral morfin geç kaldığı için DİLALTI VEYA BURUN SPREYİ FENTANİL (5-10 dakikada etki eden transmukozal form) tercih edilir.",
    "examiner_tip": "Düsseldorfer Schmerz-Klassiker: 'Sie stellen einen Tumorpatienten auf Morphin ein. Welches Rezept MUSS zwingend mitgegeben werden?' Richtige Antwort: Ein Laxans (Macrogol)! Wer die Obstipationsprophylaxe vergisst, riskiert einen tödlichen Ileus (K.O.-Kriterium). Für Durchbruchschmerzen 1/6 der Tagesdosis unretardiert verordnen!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jürinin klasik sorusu: 'Kanser hastasına morfin başladın. Yanına yazmak ZORUNDA olduğun ikinci reçete nedir?' Doğru cevap: Laksatif (Makrogol)! Kabızlık ilacını unutan hekim hastayı ileusa sokar (K.O. Kriteri). Kırılma ağrısı için günlük dozun 1/6'sı hızlı formda reçete edilir!"
  },
  {
    "id": "q_amboss_10",
    "category": "Intensivmedizin & Hirntoddiagnostik",
    "amboss_pillar": "intensiv",
    "source_book": "AMBOSS & DGAI / BDA Leitlinien-Curriculum (ÄKNO Düsseldorf)",
    "image": null,
    "question_type": "open",
    "question_de": "Ein 49-jähriger Patient erleidet eine fulminante aneurysmatische Subarachnoidalblutung (Hunt & Hess Grad V, Fisher 4). Nach interventionellem Coiling und Anlage einer externen Ventrikeldrainage kommt es zur bilateralen Mydriasis, Strecksynergismen und schließlich zum Ausfall aller Spontanbewegungen. Auf der Intensivstation soll das Vorliegen des irreversiblen Hirnfunktionsausfalls (IHA / 'Hirntod') gemäß Richtlinie der Bundesärztekammer (BÄK) festgestellt werden.\n1. Welche 3 diagnostischen Schritte fordert die BÄK-Richtlinie zur Feststellung des IHA?\n2. Welche reversiblen Ursachen müssen vor Beginn der Hirnstammreflex-Prüfung zwingend ausgeschlossen werden?\n3. Wie wird der Apnoe-Test leitliniengerecht durchgeführt und welche zwei Qualifikationen müssen die untersuchenden Ärzte aufweisen?",
    "question_tr": "49 yaşında bir hastada masif anevrizmatik subaraknoid kanama (Hunt & Hess Evre V, Fisher 4) gelişir. Girişimsel koilleme ve eksternal ventriküler drenaj takılması sonrası iki taraflı midriyazis ve ardından tüm spontan hareketlerin kaybı gelişir. Yoğun bakımda Alman Tabipler Birliği (BÄK) kılavuzuna göre Geri Dönüşümsüz Beyin Fonksiyon Kaybı (Beyin Ölümü / IHA) tespiti yapılacaktır.\n1. BÄK kılavuzu beyin ölümü tespiti için hangi 3 tanısal basamağı şart koşar?\n2. Beyin sapı reflekslerinin muayenesine başlamadan önce hangi geri döndürülebilir nedenler kesin olarak dışlanmalıdır?\n3. Apne testi kılavuza uygun olarak nasıl uygulanır ve muayeneyi yapan hekimlerin hangi niteliklere sahip olması gerekir?",
    "answer_de": "1. DIE 3 SÄULEN DER BÄK-RICHTLINIE ZUM HIRNTODNACHWEIS:\n• Schritt 1: Nachweis einer akuten, schweren primären oder sekundären Hirnschädigung (z.B. durch CCT/MRT gesicherte Massenblutung oder Trauma).\n• Schritt 2: Ausschluss aller potentiell reversiblen Ursachen für das Koma (Intoxikation, Hypothermie, Kreislaufschock, metabolische Komaformen).\n• Schritt 3: Klinischer Nachweis der Ausfallsymptome des gesamten Gehirns (Großhirn, Hirnstamm, Medulla oblongata):\n - Koma (A雙treaktivität auf Schmerzreize im Trigeminusbereich).\n - Ausfall aller Hirnstammreflexe (Pupillenreflex, Kornealreflex, Oculozephaler/Vestibulookulärer Reflex, Pharyngeal-/Trachealreflex).\n - Ausfall der Spontanatmung (positiver Apnoe-Test).\n• Nachweis der Irreversibilität: Entweder durch Beobachtungszeit (bei primärer supratentorieller Läsion 12h, bei sekundärer Hirnschädigung 72h) ODER durch ergänzende apparative Nulllinien-Diagnostik (isoelektrisches EEG über 30 min, zerebrale Perfusionsszintigraphie, Perfusions-CT oder transkranielle Dopplersonographie mit Pendelfluss).\n\n2. ZWINGENDER AUSSCHLUSS REVERSIBLER URSACHEN:\n• Keine ZNS-dämpfenden Medikamente oder Intoxikationen: Sedativa (Propofol, Midazolam), Opioide, Muskelrelaxanzien (Relaxometrie TOF zwingend 4/4!). Ggf. Substanzspiegelbestimmung im Serum oder Abwarten von mindestens 5–10 Plasmahalbwertszeiten.\n• Keine schwere Hypothermie: Die Körperkerntemperatur muss >= 35,0 °C betragen!\n• Kein Schockzustand: Der systolische Blutdruck muss >= 90 mmHg (MAP >= 60 mmHg) betragen (ggf. unter Noradrenalin).\n• Keine schweren endokrinen oder metabolischen Entgleisungen (z.B. diabetisches Koma, schwere Hyponatriämie, Urämie).\n\n3. APNOE-TEST & QUALIFIKATION DER UNTERSUCHER:\n• Apnoe-Test (Beweis des Ausfalls des Atemzentrums in der Medulla oblongata):\n - Voroxygenierung mit 100% O2 für mindestens 10–15 Minuten.\n - Diskonnektion des Beatmungsschlauchs bei kontinuierlicher trachealer O2-Insufflation (6–8 l/min O2 über feinen Katheter auf Carinaniveau zur Vermeidung von Hypoxie).\n - Blutgasanalyse (BGA): Der arterielle pCO2 muss auf mindestens >= 60 mmHg (>= 8,0 kPa) ansteigen (bei einem Anstieg von mindestens 20 mmHg über den Ausgangswert), OHNE dass Spontanatmung einsetzt!\n - Bei schwerem RR-Abfall (< 80 mmHg) oder Hypoxie: Abbruch und zwingender Wechsel auf apparative Diagnostik.\n• Qualifikation der Untersucher (Transplantationsgesetz / BÄK):\n - ZWEI unabhängige Fachärzte müssen die Diagnostik unabhängig voneinander durchführen und unterschreiben.\n - Mindestens EIN Untersucher muss Facharzt für Neurologie oder Neurochirurgie sein.\n - Beide Ärzte dürfen weder an der Organentnahme noch an der Transplantation beteiligt sein (strikte personelle Trennung!).",
    "answer_tr": "1. BEYİN ÖLÜMÜ TESPİTİNDE BÄK'NIN 3 TEMEL BASAMAĞI:\n• 1. Basamak: Akut, ağır primer veya sekonder beyin hasarının kanıtlanması (BT/MRG ile masif kanama vb.).\n• 2. Basamak: Komaya yol açabilecek tüm geri döndürülebilir nedenlerin kesin olarak dışlanması.\n• 3. Basamak: Tüm beynin klinik fonksiyon kaybının kanıtlanması:\n - Koma (ağrılı uyarana yanıtsızlık).\n - Tüm beyin sapı reflekslerinin kaybı (Işık refleksi, kornea refleksi, vestibülo-oküler refleks, öğürme/öksürük refleksi).\n - Spontan solunumun tamamen durması (Pozitif Apne Testi).\n• Geri Dönüşümsüzlüğün Kanıtı: Ya gözlem süresi beklenir (primer hasarda 12 saat, sekonder anoksik hasarda 72 saat) YA DA doğrulayıcı test yapılır (30 dk düz çizgi EEG, transkraniyal Doppler ile intrakraniyal kan akımının durduğunun gösterilmesi veya BT-anjiyografi).\n\n2. DIŞLANMASI ZORUNLU GERİ DÖNÜŞÜMLÜ NEDENLER:\n• Sedatif ilaç etkisi yokluğu: Propofol, benzodiazepin, kas gevşetici etkisi olmamalıdır (TOF testi 4/4 olmalıdır!). İlaç düzeyleri veya yarılanma ömürleri beklenmelidir.\n• Hipotermi yokluğu: Vücut iç sıcaklığı KESİNLİKLE >= 35,0 °C olmalıdır!\n• Şok yokluğu: Sistolik tansiyon >= 90 mmHg (MAP >= 60 mmHg) olmalıdır.\n• Ağır metabolik/elektrolit bozukluğu olmamalıdır.\n\n3. APNE TESTİ VE HEKİM NİTELİĞİ:\n• Apne Testi (Beyin sapı solunum merkezinin öldüğünün kanıtı):\n - %100 O2 ile 10-15 dk preoksijenizasyon yapılır.\n - Ventilatörden ayrılır, hipoksiyi önlemek için trakea içine kateterle 6-8 L/dk O2 verilir.\n - Arteryel kan gazında PaCO2 >= 60 mmHg'ye yükselene kadar (veya başlangıçtan 20 mmHg artana kadar) solunum çabası gözlenir. Solunum yoksa test POZİTİFTİR.\n• Muayeneyi Yapan Hekimlerin Nitelikleri:\n - İKİ uzman hekim birbirinden bağımsız olarak değerlendirip imzalamalıdır.\n - Hekimlerden en az biri NÖROLOJİ veya BEYİN CERRAHİSİ uzmanı olmalıdır.\n - Her iki hekim de organ nakli ve nakil ekibinde yer alamaz (çıkar çatışması yasağı!).",
    "examiner_tip": "Düsseldorfer Intensiv- & Rechtsklassiker: 'Wer darf den Hirntod feststellen und was sind die Voraussetzungen für den Apnoe-Test?' K.O.-Kriterium: 2 Fachärzte (mind. 1 Neurologe/Neurochirurg), unabhängig von der Transplantation! Apnoe-Test nur bei Kerntemperatur >= 35°C, Ausschluss von Sedativa/Relaxanzien (TOF 4/4), Ziel-pCO2 >= 60 mmHg!",
    "is_high_yield": true,
    "is_amboss_curriculum": true,
    "examiner_tip_tr": "Jüri klasiği: 'Beyin ölümünü kimler tespit edebilir ve apne testinin şartları nelerdir?' K.O. Kriteri: Biri mutlaka Nörolog veya Beyin Cerrahı olan 2 bağımsız uzman hekim! Vücut ısısı >= 35°C olmadan, sedatif etkisi varken apne testi yapılamaz. Hedef PaCO2 >= 60 mmHg'dir."
  }
];

const questionsFilePath = path.join(__dirname, '..', 'questions.js');
let content = fs.readFileSync(questionsFilePath, 'utf8');

// Check if any of these are already in
const existingIds = new Set();
for (const m of content.matchAll(/"id":\s*"([^"]+)"/g)) {
  existingIds.add(m[1]);
}

const toAdd = NEW_AMBOSS_QUESTIONS.filter(q => !existingIds.has(q.id));
console.log(`Found ${toAdd.length} new questions to add.`);

if (toAdd.length > 0) {
  const jsonStrings = toAdd.map(q => '  ' + JSON.stringify(q, null, 2).replace(/\n/g, '\n  '));
  const replacement = ',\n' + jsonStrings.join(',\n') + '\n];\n';
  
  const lastBracketIndex = content.lastIndexOf('];');
  if (lastBracketIndex === -1) {
    throw new Error('Could not find closing ]; in questions.js');
  }
  
  const newContent = content.slice(0, lastBracketIndex).trimEnd() + replacement;
  fs.writeFileSync(questionsFilePath, newContent, 'utf8');
  console.log(`Successfully appended ${toAdd.length} questions to questions.js.`);
} else {
  console.log('All questions already present.');
}
